from __future__ import annotations

from typing import Any


def emit_driver_steps_ts(catalog: dict[str, Any]) -> str:
    steps = catalog.get("steps", [])
    mapped = []
    for step in steps:
        title = step["title"].replace('"', '\\"')
        description = step["description"].replace('"', '\\"')
        selector = step["selector"].replace('"', '\\"')
        mapped.append(
            "  {\n"
            f"    element: \"{selector}\",\n"
            "    popover: {\n"
            f"      title: \"{title}\",\n"
            f"      description: \"{description}\",\n"
            "    },\n"
            "  },"
        )

    body = "\n".join(mapped)

    return (
        "// Auto-generated by tools/tutorial_generator/cli.py.\n"
        "// Scope: Accueil only (deterministic, no LLM by default).\n\n"
        "export type DriverStepConfig = {\n"
        "  element: string;\n"
        "  popover: {\n"
        "    title: string;\n"
        "    description: string;\n"
        "  };\n"
        "};\n\n"
        "export const ACCUEIL_DRIVER_STEPS: DriverStepConfig[] = [\n"
        f"{body}\n"
        "];\n"
    )
