export const PLACES = [
  {
    id: "istanbul",
  jour: [1],
    name: "Istanbul",
    shortDesc: "La ville-pont entre l'Europe et l'Asie",
    tag: "Ville",
    image: "/images/guide/Istanbul photo 1.png",
      photos: [
      "/images/guide/Istanbul photo 1.png",
      "/images/places/Mosquée bleue.png",
      "/images/places/Sainte Sophie.png",
      "/images/places/Bosphore.png",
      ],
    audioTitle: "Istanbul, entre deux mondes",
    audioDuration: "3 min 40 sec",
    audioSrc: "/audio/Histoire_de_la_Turquie.mp3",
    history:
      "Istanbul est la plus grande ville de Turquie et un point de rencontre entre deux continents. Son histoire s'étend sur des siècles, entre héritage byzantin, ottoman et vie urbaine contemporaine. C'est le meilleur point de départ pour comprendre le voyage en Turquie.",
    anecdotes: [
      "Le Bosphore coupe la ville en deux et relie la mer Noire à la mer de Marmara.",
      "On peut passer d'un continent à l'autre en quelques minutes seulement.",
      "Les quartiers historiques et les rives modernes donnent à la ville des visages très différents.",
    ],
  },
  {
    id: "sainte-sophie",
    jour: [2],
    name: "Sainte-Sophie",
    shortDesc: "Chef-d'œuvre byzantin aux mille histoires",
    tag: "Monument",
    image: "/images/Jour 2/Sainte-Sophie.webp",
    photos: [
      "/images/Jour 2/Sainte-Sophie.webp",
    ],
    audioTitle: "Sainte-Sophie, symbole d'Istanbul",
    audioDuration: "3 min 20 sec",
    audioSrc: "/audio/places/Sainte-Sophie.mp3",
    history:
      "Ancienne basilique byzantine devenue mosquée, puis musée, puis mosquée à nouveau, Sainte-Sophie est l'un des monuments les plus emblématiques d'Istanbul. Construite au VIe siècle sous Justinien, sa gigantesque coupole a fasciné pendant des siècles.",
    anecdotes: [
      "Sainte-Sophie signifie 'Sagesse divine' en grec.",
      "La coupole principale mesure 31 mètres de diamètre.",
      "Elle a servi de modèle pour de nombreuses mosquées ottomanes, dont la Mosquée Bleue.",
    ],
  },
  {
    id: "citerne-basilique",
    jour: [2],
    name: "Citerne Basilique",
    shortDesc: "Un palais souterrain aux colonnes mystérieuses",
    tag: "Monument",
    image: "/images/Jour 2/citerne-basilique 1.webp",
    photos: [
      "/images/Jour 2/citerne-basilique 1.webp",
      "/images/Jour 2/citerne-basilique 2.webp",
    ],
    audioTitle: "Les secrets de la Citerne Basilique",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/places/Citerne_basilique.mp3",
    history:
      "Construite au VIe siècle sous l'empereur Justinien, la Citerne Basilique est un immense réservoir souterrain qui servait à stocker l'eau de la ville. Ses 336 colonnes et son atmosphère feutrée en font un lieu unique.",
    anecdotes: [
      "La citerne peut contenir jusqu'à 80 000 m³ d'eau.",
      "Deux colonnes reposent sur des bases en forme de tête de Méduse, dont l'origine reste mystérieuse.",
      "Elle est surnommée 'Palais immergé' par les Ottomans.",
    ],
  },
  {
    id: "kadikoy",
    jour: [2],
    name: "Kadıköy (Kadıköy Çarşısı)",
    shortDesc: "Le cœur branché de la rive asiatique",
    tag: "Quartier",
    image: "/images/Jour 2/kadikoy 1.webp",
    photos: [
      "/images/Jour 2/Kadikoy 1.webp",
      "/images/Jour 2/Kadikoy 2.webp",
    ],
    audioTitle: "Kadıköy, l'âme asiatique d'Istanbul",
    audioDuration: "3 min 10 sec",
    audioSrc: "/audio/places/Kadikoy.mp3",
    history:
      "Kadıköy est l'un des quartiers les plus vivants de la rive asiatique d'Istanbul. Son marché (çarşı) regorge de produits frais, d'épices, de poissons et de boutiques locales. C'est un lieu de rencontre authentique, loin du tourisme de masse.",
    anecdotes: [
      "Aperçu de la Tour de Léandre depuis le bateau vers Kadıköy.",
      "Kadıköy est réputé pour ses rues piétonnes et ses cafés branchés.",
      "Le marché de Kadıköy est l'un des plus anciens de la ville.",
    ],
  },
  {
    id: "mosquee-suleymaniye",
    jour: [2],
    name: "Mosquée Süleymaniye",
    shortDesc: "La mosquée de Soliman le Magnifique",
    tag: "Monument",
    image: "/images/Jour 2/suleymaniye 1.webp",
    photos: [
      "/images/Jour 2/suleymaniye 1.webp",
      "/images/Jour 2/suleymaniye 2.webp",
    ],
    audioTitle: "La Süleymaniye, chef-d'œuvre de Sinan",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Suleymaniye.mp3",
    history:
      "Construite entre 1550 et 1557 par l'architecte impérial Sinan pour le sultan Soliman le Magnifique, la Süleymaniye est la plus grande mosquée d'Istanbul. Elle domine la ville du haut de sa colline et offre une vue panoramique exceptionnelle.",
    anecdotes: [
      "L'architecte Sinan considérait la Süleymaniye comme son chef-d'œuvre.",
      "Les quatre minarets symbolisent le rang de Soliman, le quatrième sultan après la conquête.",
      "La mosquée abrite les tombeaux de Soliman et de sa femme Roxelane.",
    ],
  },
  {
    id: "croisiere-bosphore",
    jour: [2],
    name: "Croisière sur le Bosphore",
    shortDesc: "Entre deux continents, entre deux mondes",
    tag: "Activité",
    image: "/images/Jour 2/croisiere bosphore 1.jpg",
    photos: [
      "/images/Jour 2/croisiere bosphore 1.jpg",
      "/images/Jour 2/croisiere bosphore 2.jpg",
    ],
    audioTitle: "Le Bosphore, frontière liquide",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Croisiere_Bosphore.mp3",
    history:
      "La croisière sur le Bosphore est l'une des expériences incontournables d'Istanbul. Ce détroit reliant la mer Noire à la mer de Marmara sépare l'Europe de l'Asie et offre des vues spectaculaires sur les palais, les mosquées et les villas ottomanes qui bordent ses rives.",
    anecdotes: [
      "Le Bosphore mesure environ 32 km de long.",
      "On peut voir le palais de Dolmabahçe, le palais de Çırağan et le fort de Rumeli Hisarı depuis le bateau.",
      "Des dauphins sont parfois aperçus dans le détroit.",
    ],
  },
  {
    id: "dolmabahce",
    jour: [2],
    name: "Palais de Dolmabahçe",
    shortDesc: "Le palais baroque des sultans",
    tag: "Monument",
    image: "/images/Jour 2/Dolmabahce 1.webp",
    photos: [
      "/images/Jour 2/Dolmabahce 1.webp",
    ],
    audioTitle: "Dolmabahçe, fastes du XIXe siècle",
    audioDuration: "3 min 15 sec",
    audioSrc: "/audio/places/Dolmabahce.mp3",
    history:
      "Construit au milieu du XIXe siècle, le palais de Dolmabahçe fut la résidence principale des sultans ottomans jusqu'à la chute de l'Empire. Mêlant styles baroque, rococo et néoclassique, il impressionne par son luxe et sa monumentalité. On passe devant le stade de football à proximité.",
    anecdotes: [
      "Le palais possède le plus grand lustre de cristal de Bohême du monde, avec 750 lampes.",
      "Atatürk y est décédé le 10 novembre 1938.",
      "Passage devant le stade de football à proximité du palais.",
    ],
  },
  {
    id: "saint-sauveur-chora",
    jour: [2],
    name: "Saint-Sauveur in Chora",
    shortDesc: "Un trésor de mosaïques byzantines",
    tag: "Monument",
    image: "/images/Jour 2/Sainte-Sauveur in Chora 1.webp",
    photos: [ 
      "/images/Jour 2/Sainte-Sauveur in Chora 1.webp",
      "/images/Jour 2/Sainte-Sauveur in Chora 2.webp",
      "/images/Jour 2/Sainte-Sauveur in Chora 3.webp",
    ],
    audioTitle: "Chora, la beauté cachée",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Sainte_Sauveur_Chora.mp3",
    history:
      "L'église Saint-Sauveur in Chora, aujourd'hui musée (Kariye), est célèbre pour ses mosaïques et fresques byzantines parmi les plus belles qui subsistent. Datant du XIVe siècle, ces œuvres illustrent des scènes de la vie du Christ et de la Vierge avec une finesse exceptionnelle.",
    anecdotes: [
      "'Chora' signifie 'hors les murs' en grec, car l'église se trouvait à l'origine en dehors des remparts de Constantinople.",
      "Les mosaïques ont été réalisées entre 1315 et 1321.",
      "Le lieu est souvent moins fréquenté que Sainte-Sophie, ce qui permet une visite plus sereine.",
    ],
  },
  {
    id: "mosquee-ortakoy",
    jour: [2],
    name: "Mosquée Büyük Mecidiye d'Ortaköy",
    shortDesc: "La mosquée de la photo iconique",
    tag: "Monument",
    image: "/images/Jour 2/Mosquée Buyuk 1.webp",
    photos: [
      "/images/Jour 2/Mosquée Buyuk 1.webp",
      "/images/Jour 2/Mosquée Buyuk 2.webp",
    ],
    audioTitle: "Ortaköy, la mosquée du Bosphore",
    audioDuration: "2 min 40 sec",
    audioSrc: "/audio/places/Mosquee_Ortakoy.mp3",
    history:
      "Située au bord du Bosphore, juste sous le pont suspendu, la Mosquée Büyük Mecidiye d'Ortaköy est l'un des symboles les plus photographiés d'Istanbul. Construite au XIXe siècle dans un style néo-baroque, elle offre un contraste saisissant avec le pont moderne qui la surplombe.",
    anecdotes: [
      "C'est le lieu de la photo la plus connue et partagée d'Istanbul.",
      "Le quartier d'Ortaköy est réputé pour ses kumpir (pommes de terre farcies) et ses gaufres.",
      "La mosquée est particulièrement belle au coucher du soleil.",
    ],
  },
  {
    id: "croisiere-nocturne",
    jour: [2],
    name: "Croisière nocturne",
    shortDesc: "Istanbul illuminée depuis l'eau",
    tag: "Activité",
    image: "/images/Jour 2/croisiere nocturne 2.webp",
    photos: [
      "/images/Jour 2/croisiere nocturne 2.webp",
    ],
    audioTitle: "Istanbul la nuit, du Bosphore",
    audioDuration: "2 min 30 sec",
    audioSrc: "/audio/places/Croisiere_Nocturne.mp3",
    history:
      "La croisière nocturne sur le Bosphore offre une perspective magique sur Istanbul. Les palais, les mosquées et les ponts illuminés se reflètent dans l'eau, créant une atmosphère féerique et romantique.",
    anecdotes: [
      "Le pont du Bosphore est illuminé de mille feux la nuit.",
      "Le palais de Dolmabahçe est particulièrement spectaculaire vu depuis l'eau à la tombée de la nuit.",
      "C'est une expérience incontournable pour les amoureux de la ville.",
    ],
  },
  {
    id: "restaurant-vina-garden",
    jour: [2],
    name: "La Vina Garden 1864 Restaurant",
    shortDesc: "Une table à réserver à Sultanahmet",
    tag: "Restaurant",
    image: "/images/Jour 2/Restau Jour 2.1.webp",
    photos: [
      "/images/Jour 2/Restau Jour 2.1.webp",
      "/images/Jour 2/Restau Jour 2.2.webp",
    ],
    audioTitle: "Gastronomie à Sultanahmet",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Vina_Garden.mp3",
    history:
      "Situé dans le quartier historique de Sultanahmet, La Vina Garden 1864 propose une cuisine raffinée dans un cadre élégant. C'est une adresse à réserver pour profiter d'un dîner de qualité au cœur de la vieille ville.",
    anecdotes: [
      "À réserver impérativement.",
      "Situé à Sultanahmet, à proximité des principaux monuments.",
      "Le restaurant propose une carte mêlant cuisine turque traditionnelle et créations modernes.",
    ],
  },
  {
  id: "topkapi",
  jour: [3],
  name: "Palais de Topkapi",
  shortDesc: "Le cœur du pouvoir des sultans ottomans pendant près de quatre siècles",
  tag: "Monument",
  image: "/images/Jour 3/Topkapi/Topkapi 2.png",
  photos: [
    "/images/Jour 3/Topkapi/Topkapi 0.png",
    "/images/Jour 3/Topkapi/Topkapi 1.png",
    "/images/Jour 3/Topkapi/Topkapi 2.png",
    "/images/Jour 3/Topkapi/Topkapi 3.png",
    "/images/Jour 3/Topkapi/Topkapi 4.png",
    ],
  audioTitle: "Découvrez le Palais de Topkapi",
  audioDuration: "4 min 20 sec",
  audioSrc: "/audio/places/Le_palais_de_Topkapi.mp3",
  history:
    "Construit à partir de 1459 sur les ordres du sultan Mehmed II, peu après la conquête de Constantinople, le Palais de Topkapi fut la résidence officielle des sultans ottomans et le centre administratif de l'Empire pendant près de quatre siècles. Véritable ville dans la ville, il abritait les appartements impériaux, le harem, les cuisines, le trésor et les salles où étaient prises les décisions qui influençaient une grande partie du monde méditerranéen et du Moyen-Orient.",
  anecdotes: [
    "Le palais compte quatre grandes cours successives, chacune plus privée que la précédente.",
    "Le Harem impérial pouvait accueillir plusieurs centaines de personnes, dont la famille du sultan et ses serviteurs.",
    "Le Trésor de Topkapi expose le célèbre poignard de Topkapi ainsi que le diamant du fabricant de cuillères, l'un des plus grands diamants exposés au monde.",
    "Depuis les terrasses du palais, la vue sur le Bosphore, la Corne d'Or et la mer de Marmara est spectaculaire.",
    "Le palais conserve plusieurs reliques sacrées de l'islam, notamment des objets traditionnellement attribués au prophète Mahomet."
  ],
},
  {
    id: "mosquee-bleue",
    jour: [3],
    name: "Mosquée Bleue",
    shortDesc: "La mosquée aux six minarets et 21 403 faïences",
    tag: "Monument",
    image: "/images/Jour 3/Mosquee bleue 1.webp",
    photos: [
      "/images/Jour 3/Mosquee bleue 1.webp",
      "/images/Jour 3/Mosquee bleue 2.webp",
      "/images/Jour 3/Mosquee bleue 3.webp",
    ],
    audioTitle: "La Mosquée Bleue, merveille ottomane",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Mosquee_Bleue.mp3",
    history:
      "Construite au XVIIe siècle sous le sultan Ahmet Ier, la Mosquée Bleue (Sultanahmet Camii) est l'un des monuments les plus célèbres d'Istanbul. Elle doit son surnom aux 21 403 faïences bleues d'Iznik qui ornent son intérieur. Ses six minarets en font une mosquée unique à l'époque de sa construction.",
    anecdotes: [
      "Elle compte 21 403 faïences bleues d'Iznik.",
      "Ses six minarets ont provoqué un scandale à l'époque, car seule la mosquée de La Mecque en possédait autant.",
      "Le sultan Ahmet Ier a dû financer une septième minareth à La Mecque pour apaiser les critiques.",
    ],
  },
  {
    id: "hippodrome-byzantin",
    jour: [3],
    name: "Hippodrome byzantin",
    shortDesc: "Le cœur antique de Constantinople",
    tag: "Monument",
    image: "/images/Jour 3/Hippodrome 1.webp",
    photos: [
      "/images/Jour 3/Hippodrome 1.webp",
    ],
    audioTitle: "L'Hippodrome, théâtre de l'Empire",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Hippodrome_Byzantin.mp3",
    history:
      "L'Hippodrome de Constantinople était le centre de la vie publique de la ville byzantine. C'est ici que se déroulaient les courses de chars et les cérémonies impériales. Aujourd'hui, la place conserve trois obélisques antiques qui témoignent de son prestigieux passé.",
    anecdotes: [
      "L'obélisque de Théodose date de l'Égypte antique (XVe siècle av. J.-C.) et fut érigé ici en 390.",
      "La colonne serpentine fut rapportée de Delphes par Constantin.",
      "L'hippodrome pouvait accueillir jusqu'à 100 000 spectateurs.",
    ],
  },
  {
    id: "place-taksim",
    jour: [3],
    name: "Place de Taksim",
    shortDesc: "Le cœur battant de l'Istanbul moderne",
    tag: "Quartier",
    image: "/images/Jour 3/Taksim 1.webp",
    photos: [
      "/images/Jour 3/Taksim 1.webp",
      "/images/Jour 3/Taksim 2.webp",
    ],
    audioTitle: "Taksim, carrefour de la vie stambouliote",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/places/Place_Taksim.mp3",
    history:    
      "La place de Taksim est le centre névralgique de l'Istanbul moderne. Entourée de commerces, d'hôtels et de restaurants, elle est le point de départ de l'avenue Istiklal et un lieu de rassemblement pour les Stambouliotes.",
    anecdotes: [  
      "Le Monument de la République au centre de la place date de 1928.",
      "Taksim signifie 'distribution' en turc, car c'est ici que l'eau était distribuée à la ville.",
      "C'est le point de départ de l'avenue Istiklal, artère commerçante de 1,4 km.",
    ],
  },
  {
    id: "pera-tour",
    jour: [3],
    name: "Quartier de Péra",
    shortDesc: "L'élégance d'antan au cœur de Beyoğlu",
    tag: "Quartier",
    image: "/images/Jour 3/Pera Galata 1.webp",
    photos: [
      "/images/Jour 3/Pera Galata 1.webp",
      "/images/Jour 3/Pera Galata 2.webp",
    ],
    audioTitle: "Péra, l'âme cosmopolite d'Istanbul",
    audioDuration: "3 min 40 sec",
    audioSrc: "/audio/places/Quartier_de_Pera.mp3",
    history:
      "Au début du XXe siècle, le quartier de Péra (aujourd'hui Beyoğlu) était la fierté de la ville. Ambassades, prestigieuses écoles, immeubles bourgeois, théâtres, cinémas, restaurants et tavernes s'y côtoiaient. C'est ici que la société élite stambouliote fréquentait. La Tour Galata, vestige médiéval, domine le quartier de ses 67 mètres.",
    anecdotes: [
      "Au début du XXe siècle, ce quartier était la fierté de la ville.",
      "Ambassades, prestigieuses écoles, immeubles bourgeois, théâtres, cinémas, restaurants et tavernes, c'est ici que la société élite stambouliote fréquentait.",
    ],
  },
  {
  id: "tour-galata",
  jour: [3],
  name: "Tour de Galata",
  shortDesc: "Un emblème médiéval dominant Istanbul depuis près de 700 ans",
  tag: "Monument",
  image: "/images/Jour 3/Tour Galata 1.webp",
  photos: [
    "/images/Jour 3/Tour Galata 1.webp",
    "/images/Jour 3/Tour Galata 2.webp",
  ],
  audioTitle: "La Tour de Galata, sentinelle d'Istanbul",
  audioDuration: "3 min 30 sec",
  audioSrc: "/audio/places/Tour_Galata.mp3",
  history:
    "Construite en 1348 par les Génois installés dans le quartier de Galata, la Tour de Galata est l'un des monuments les plus emblématiques d'Istanbul. Haute de près de 67 mètres, elle servait autrefois de tour de défense et de surveillance sur les remparts de la colonie génoise. Transformée au fil des siècles en prison, observatoire puis point de départ des premières expériences aériennes d'Hezarfen Ahmed Çelebi, elle offre aujourd'hui l'un des plus beaux panoramas sur le Bosphore, la Corne d'Or, la vieille ville et les collines d'Istanbul.",
  anecdotes: [
    "Construite en 1348 par les Génois, la Tour de Galata est l'un des plus anciens monuments médiévaux encore visibles à Istanbul.",
    "Selon la légende, au XVIIe siècle, Hezarfen Ahmed Çelebi se serait élancé depuis la tour avec des ailes artificielles pour traverser le Bosphore en volant.",
    "Son sommet offre une vue spectaculaire à 360 degrés sur Sainte-Sophie, la Mosquée Bleue, le Palais de Topkapi et le détroit du Bosphore.",
  ],
},
  {
    id: "restaurant-jour3",
    jour: [3],
    name: "Restaurant à réserver (Taksim ou rooftop hôtel)",
    shortDesc: "Dîner avec vue sur la ville",
    tag: "Restaurant",
    image: "/images/Jour 3/Restau Jour 3.webp",
    photos: [
      "/images/Jour 3/Restau Jour 3.webp",
    ],
    audioTitle: "Dîner panoramique à Istanbul",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Restaurant_Taksim.mp3",
    history:
      "Pour clore cette journée de découverte, une table à réserver soit dans le quartier animé de Taksim, soit en rooftop de l'hôtel pour profiter d'une vue imprenable sur Istanbul illuminée.",
    anecdotes: [
      "À réserver impérativement.",
      "Option Taksim : ambiance branchée et cuisine variée.",
      "Option rooftop hôtel : vue panoramique sur la ville et la Corne d'Or.",
    ],
  },
{
    id: "cappadoce",
  jour: [4],
    name: "Cappadoce",
    shortDesc: "Des vallées sculptées et des montgolfières au lever du soleil",
    tag: "Nature",
    image:
      "https://images.unsplash.com/photo-1539650116574-75c0c6d9f25f?w=800&h=500&fit=crop&auto=format",
    photos: [
      "https://images.unsplash.com/photo-1539650116574-75c0c6d9f25f?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1507608616759-54f48f0af0ee?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1516550893885-8a3a9d7a7d42?w=800&h=500&fit=crop&auto=format",
    ],
    audioTitle: "Cappadoce au lever du soleil",
    audioDuration: "2 min 55 sec",
    audioSrc: "/audio/places/cappadoce.mp3",
    history:
      "La Cappadoce est célèbre pour ses paysages de roche volcanique, ses vallées et ses habitations creusées dans la pierre. La région a longtemps servi de refuge et de lieu de passage pour différentes civilisations.",
    anecdotes: [
      "Les montgolfières colorent le ciel au lever du soleil dans une ambiance très particulière.",
      "Des cités souterraines ont servi d'abri à de nombreuses communautés au fil du temps.",
      "Les formations rocheuses donnent au paysage un aspect presque irréel.",
    ],
  },
  {
    id: "pamukkale",
  jour: [5],
    name: "Pamukkale",
    shortDesc: "Des terrasses blanches comme du coton et des sources chaudes",
    tag: "Nature",
    image:
      "https://images.unsplash.com/photo-1540966593321-9e5d5b5cf8b2?w=800&h=500&fit=crop&auto=format",
    photos: [
      "https://images.unsplash.com/photo-1540966593321-9e5d5b5cf8b2?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1519955266818-1e1f0b3c8af6?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1505731133484-93b3a8a8f7d9?w=800&h=500&fit=crop&auto=format",
    ],
    audioTitle: "Pamukkale, le château de coton",
    audioDuration: "3 min 05 sec",
    audioSrc: "/audio/pamukkale.mp3",
    history:
      "Pamukkale est connue pour ses bassins de travertin blancs formés par des eaux riches en minéraux. Le site est à la fois spectaculaire et chargé d'histoire, avec les ruines antiques de Hiérapolis à proximité.",
    anecdotes: [
      "Les terrasses blanches ont donné à Pamukkale son surnom de château de coton.",
      "Les bassins naturels se forment grâce aux dépôts minéraux de l'eau chaude.",
      "Le site combine paysage naturel et vestiges antiques dans une même visite.",
    ],
  },
  {
    id: "ephese",
  jour: [6],
    name: "Site d'Éphèse",
    shortDesc: "Des ruines antiques parmi les plus impressionnantes du pays",
    tag: "Histoire",
    image:
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&h=500&fit=crop&auto=format",
    photos: [
      "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1568393413901-1bd87d6c7f84?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1587474260584-136574528ed5?w=800&h=500&fit=crop&auto=format",
    ],
    audioTitle: "Éphèse, cité de pierre",
    audioDuration: "3 min 15 sec",
    audioSrc: "/audio/ephese.mp3",
    history:
      "Éphèse est l'un des sites antiques les plus célèbres de Turquie. Ancienne cité grecque puis romaine, elle abrite des vestiges remarquablement conservés comme la bibliothèque de Celsus et un immense théâtre.",
    anecdotes: [
      "La bibliothèque de Celsus est l'un des monuments les plus photographiés du site.",
      "Le grand théâtre pouvait accueillir des milliers de spectateurs.",
      "Le site permet de ressentir très concrètement la grandeur des cités antiques.",
    ],
  },
  {
    id: "izmir",
  jour: [7],
    name: "Izmir",
    shortDesc: "Une grande ville côtière vivante et ouverte sur la mer Égée",
    tag: "Ville",
    image:
      "https://images.unsplash.com/photo-1587502536263-0c7d35f1b7f7?w=800&h=500&fit=crop&auto=format",
    photos: [
      "https://images.unsplash.com/photo-1587502536263-0c7d35f1b7f7?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1500375592092-40eb2168fd21?w=800&h=500&fit=crop&auto=format",
    ],
    audioTitle: "Izmir au bord de l'Égée",
    audioDuration: "2 min 45 sec",
    audioSrc: "/audio/izmir.mp3",
    history:
      "Izmir est une grande ville portuaire du littoral égéen. Moderne, animée et agréable à parcourir, elle combine front de mer, marchés, cafés et quartiers historiques.",
    anecdotes: [
      "La promenade du Kordon est l'un des lieux préférés pour flâner au bord de l'eau.",
      "Le centre-ville mélange architecture contemporaine et traces de son passé maritime.",
      "La ville est souvent vue comme l'une des plus détendues et ouvertes de Turquie.",
    ],
  },
  {
    id: "bursa",
  jour: [8],
    name: "Bursa",
    shortDesc: "Une ancienne capitale ottomane entre patrimoine et montagne",
    tag: "Patrimoine",
    image:
      "https://images.unsplash.com/photo-1517549556773-5c6a1f0b0f4d?w=800&h=500&fit=crop&auto=format",
    photos: [
      "https://images.unsplash.com/photo-1517549556773-5c6a1f0b0f4d?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1524230507669-5d8c5fbf2a0d?w=800&h=500&fit=crop&auto=format",
      "https://images.unsplash.com/photo-1493246507139-91e8fad9978e?w=800&h=500&fit=crop&auto=format",
    ],
    audioTitle: "Bursa, héritage ottoman",
    audioDuration: "3 min 10 sec",
    audioSrc: "/audio/bursa.mp3",
    history:
      "Bursa a été l'une des premières capitales de l'Empire ottoman. La ville est connue pour ses mosquées historiques, ses marchés, son mont Uludağ et une ambiance plus paisible que les grandes métropoles côtières.",
    anecdotes: [
      "Le mont Uludağ attire aussi bien les visiteurs d'été que les amateurs de neige en hiver.",
      "La ville conserve une forte identité ottomane dans son architecture et ses marchés.",
      "Bursa est souvent associée à une visite plus douce, plus verte et plus locale.",
    ],
  },
];