export const PLACES = [
{
    id: "Découverte de la Turquie",
    jour: [1],
    name: "La Turquie en résumé",
    shortDesc: "La Turquie en résumé",
    tag: "Découvrir",
    image: "/images/Geographie/drapeau_photo_1.webp",
    photos: [
      "/images/Geographie/drapeau_photo_1.webp",
    ],
    historyLabel:"La Turquie en résumé", 
    history:
      "Nous embarquons vers la Turquie. Quelques informations rapides ci-dessous. Pour en savoir plus, consulter le guide du voyage et les sections détaillées de l'application de vacances.\n"+
      "\n"+
      "La Turquie est une destination avec toutes sortes de paysages pour le bonheur de tous. Ce pays est situé sur deux continents, principalement en Asie et 3% en Europe avec une population de plus de 83 millions d’habitants en 2020. Elle a des frontières avec la Grèce, la Bulgarie, la Géorgie, l’Arménie, l’Azerbaïdjan, l’Iran, l’Irak et la Syrie.\n"+
      "**La République de Turquie a été fondée en 1923 par Mustafa Kemal Atatürk**. Ce jeune pays offre une richesse au niveau historique grâce aux anciens empires grec, perse, romain, byzantin et ottoman qui permet de voyager à travers le temps à travers ses terres chargée d’histoires.",
    anecdotesLabel: "informations générales",
    anecdotes: [
      "Superficie : 783 562 km2",
      "Nombre d’habitants : 84 millions",
      "Point culminant : Mont Ararat (5165m)",
      "Longueur de côtes : 7200km",
      "Statut : République laïque",
      "Capitale : Ankara",
    ],
  },
  {
    id: "Nante-Paris",
    reservationDocumentIds: ["vol-nantes-paris-af7507"],
    jour: [1],
    name: "Nantes - Paris",
    shortDesc: "Vol AF7507 - 19h45 -> 20h55",
    tag: "Vol",
    ville: "Nantes",
    image: "/images/Vol/Nantes Paris.webp",
    photos: [
      "/images/Vol/Nantes Paris.webp",
    ],
    historyLabel:"Détails du vol", 
    history:
      "Vol **AF7507** de Nantes (NTE) à Paris Charles de Gaulle (CDG). Départ à **19h45** pour une arrivée à 20h55\n"+
      "L'arrivée à Charles de Gaulle se fait à l'aéroport 2F\n"+
      "**Réservation** : ZT59SQ",
    anecdotesLabel: "Informations bagages",
    gps: "47.1532,-1.6107",
    anecdotes: [
      "Petit sac à ranger devant soi : 40 x 30 x 15 cm",
      "Valise cabine à ranger dans le compartiment supérieur : 55 x 25 x 35 cm",
      "Le poids total des bagages à main ne doit pas dépasser 12 kg",
      "Bagages en soute de 23 kg maximum",
    ],
  },
  {
    id: "Paris-istanbul",
    reservationDocumentIds: ["vol-paris-istanbul-af1390"],
    jour: [1],
    name: "Paris - Istanbul",
    shortDesc: "Vol AF1390 - 22h55 -> 03h30",
    tag: "Vol",
    ville: "Paris",
    image: "/images/Vol/Paris Istanbul.webp",
    photos: [
      "/images/Vol/Paris Istanbul.webp",
    ],
    historyLabel:"Détails du vol", 
    history:
      "Vol **AF1390** de Paris Charles de Gaulle (CDG) à Istanbul (IST). Départ à **22h55** pour une arrivée à **03h30**\n"+
      "Le départ se fait de l'aéroport Charles de Gaulle 2E\n"+
      "**Réservation** : ZT59SQ",
    anecdotesLabel: "Informations bagages",
    gps: "49.0097,2.5479",
    anecdotes: [
            "Petit sac à ranger devant soi : 40 x 30 x 15 cm",
      "Valise cabine à ranger dans le compartiment supérieur : 55 x 25 x 35 cm",
      "Le poids total des bagages à main ne doit pas dépasser 12 kg",
      "Bagages en soute de 23 kg maximum",
    ],
  },
  {
    id: "istanbul",
    jour: [2],
    name: "Istanbul",
    shortDesc: "La ville-pont entre l'Europe et l'Asie",
    tag: "Ville",
    ville: "Istanbul",
    image: "/images/guide/Istanbul photo 1.webp",
    photos: [
      "/images/guide/Istanbul photo 1.webp",
      "/images/places/Mosquée bleue.webp",
      "/images/places/Sainte Sophie.webp",
      "/images/places/Bosphore.webp",
    ],
    audioTitle: "Istanbul, entre deux mondes",
    audioDuration: "3 min 40 sec",
    audioSrc: "/audio/places/Istanbul.mp3",
    historyLabel:"Présentation",
    history:
      "Istanbul est la plus grande ville de Turquie et un point de rencontre entre deux continents. Son histoire s'étend sur des siècles, entre héritage byzantin, ottoman et vie urbaine contemporaine. C'est le meilleur point de départ pour comprendre le voyage en Turquie.",
    anecdotes: [
      "Le Bosphore coupe la ville en deux et relie la mer Noire à la mer de Marmara.",
      "On peut passer d'un continent à l'autre en quelques minutes seulement.",
      "Les quartiers historiques et les rives modernes donnent à la ville des visages très différents.",
    ],
    links: [
      {
        label: "(C'est pas sorcier) Comment Istanbul a régné sur 3 continents",
        url: "https://youtu.be/9_33Rx3R-yA?si=bIOrMgeBoWe_cWvx",
      },
      { 
        label: "(C'est pas sorcier) Où se trouve Istanbul ?",
        url: "https://youtu.be/lftdAxMAoQM?si=B_RmFsKX2CTP3ouv",
      },          
    ],
  },
  {
    id: "sainte-sophie",
    jour: [2],
    name: "Sainte-Sophie",
    shortDesc: "Chef-d'œuvre byzantin aux mille histoires",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 2/sainte_sophie_photo_1.webp",
    photos: [
      "/images/Jour 2/sainte_sophie_photo_1.webp",
      "/images/Jour 2/Sainte-Sophie.webp",
      "/images/Jour 2/plan sainte sophie.webp",
    ],
    audioTitle: "Sainte-Sophie, symbole d'Istanbul",
    audioDuration: "3 min 20 sec",
    audioSrc: "/audio/places/Sainte-Sophie.mp3",
    gps: "41.0086,28.9802",
    history:
      "Ancienne basilique byzantine devenue mosquée, puis musée, puis mosquée à nouveau, Sainte-Sophie est l'un des monuments les plus emblématiques d'Istanbul. Construite au VIe siècle sous Justinien, sa gigantesque coupole a fasciné pendant des siècles.",
    anecdotes: [
      "Sainte-Sophie signifie 'Sagesse divine' en grec.",
      "La coupole principale mesure 31 mètres de diamètre.",
      "Elle a servi de modèle pour de nombreuses mosquées ottomanes, dont la Mosquée Bleue.",
    ],
  },
  {
    id: "citerne-basilique",
    jour: [2],
    name: "Citerne Basilique",
    shortDesc: "Un palais souterrain aux colonnes mystérieuses",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 2/citerne-basilique 1.webp",
    photos: [
      "/images/Jour 2/citerne-basilique 1.webp",
      "/images/Jour 2/citerne-basilique 2.webp",
    ],
    audioTitle: "Les secrets de la Citerne Basilique",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/places/Citerne_basilique.mp3",
    gps: "41.0084,28.9779",
    history:
      "Construite au VIe siècle sous l'empereur Justinien, la Citerne Basilique est un immense réservoir souterrain qui servait à stocker l'eau de la ville. Ses 336 colonnes et son atmosphère feutrée en font un lieu unique.",
    anecdotes: [
      "La citerne peut contenir jusqu'à 80 000 m³ d'eau.",
      "Deux colonnes reposent sur des bases en forme de tête de Méduse, dont l'origine reste mystérieuse.",
      "Elle est surnommée 'Palais immergé' par les Ottomans.",
    ],
  },
  {
    id: "mosquee-suleymaniye",
    jour: [2],
    name: "Mosquée Süleymaniye",
    shortDesc: "La mosquée de Soliman le Magnifique",
    tag: "Visite",
    ville: "Istanbul",  
    image: "/images/Jour 2/suleymaniye 1.webp",
    photos: [
      "/images/Jour 2/suleymaniye 1.webp",
      "/images/Jour 2/suleymanyie_photo_1.webp",
      "/images/Jour 2/suleymaniye 2.webp",
    ],
    audioTitle: "La Süleymaniye, chef-d'œuvre de Sinan",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Suleymaniye.mp3",
    gps: "41.0162,28.9637",
    history:
      "Construite entre 1550 et 1557 par l'architecte impérial Sinan pour le sultan Soliman le Magnifique, la Süleymaniye est la plus grande mosquée d'Istanbul. Elle domine la ville du haut de sa colline et offre une vue panoramique exceptionnelle.",
    anecdotes: [
      "L'architecte Sinan considérait la Süleymaniye comme son chef-d'œuvre.",
      "Les quatre minarets symbolisent le rang de Soliman, le quatrième sultan après la conquête.",
      "La mosquée abrite les tombeaux de Soliman et de sa femme Roxelane.",
    ],
  },
  {
    id: "dolmabahce",
    jour: [2],
    name: "Palais de Dolmabahçe",
    shortDesc: "Le palais baroque des sultans",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 2/Dolmabahce 1.webp",
    photos: [
      "/images/Jour 2/Dolmabahce 1.webp",
      "/images/Jour 2/dolmabahce_photo_1.webp",
    ],
    audioTitle: "Dolmabahçe, fastes du XIXe siècle",
    audioDuration: "3 min 15 sec",
    audioSrc: "/audio/places/Dolmabahce.mp3",
    gps: "41.0392,29.0007",
    history:
      "Construit au milieu du XIXe siècle, le palais de Dolmabahçe fut la résidence principale des sultans ottomans jusqu'à la chute de l'Empire. Mêlant styles baroque, rococo et néoclassique, il impressionne par son luxe et sa monumentalité. On passe devant le stade de football à proximité.",
    anecdotes: [
      "Le palais possède le plus grand lustre de cristal de Bohême du monde, avec 750 lampes.",
      "Atatürk y est décédé le 10 novembre 1938.",
      "Passage devant le stade de football du Beşiktaş JK à proximité du palais.",
    ],
  },
  {
    id: "mosquee-ortakoy",
    jour: [2],
    name: "Mosquée Büyük Mecidiye d'Ortaköy",
    shortDesc: "La mosquée de la photo iconique",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 2/Mosquée Büyük Mecidiye d’Ortakoy.webp",
    photos: [
      "/images/Jour 2/Mosquée Büyük Mecidiye d’Ortakoy.webp",
      "/images/Jour 2/Mosquée Buyuk 1.webp",
      "/images/Jour 2/Mosquée Buyuk 2.webp",
    ],
    audioTitle: "Ortaköy, la mosquée du Bosphore",
    audioDuration: "2 min 40 sec",
    audioSrc: "/audio/places/Mosquee_Ortakoy.mp3",
    gps: "41.0473,29.0260",
    history:
      "Située au bord du Bosphore, juste sous le pont suspendu, la Mosquée Büyük Mecidiye d'Ortaköy est l'un des symboles les plus photographiés d'Istanbul. Construite au XIXe siècle dans un style néo-baroque, elle offre un contraste saisissant avec le pont moderne qui la surplombe.",
    anecdotes: [
      "C'est le lieu de la photo la plus connue et partagée d'Istanbul.",
      "Le quartier d'Ortaköy est réputé pour ses kumpir (pommes de terre farcies) et ses gaufres.",
      "La mosquée est particulièrement belle au coucher du soleil.",
    ],
  },
  {
    id: "kadikoy",
    jour: [2],
    name: "Promenade et achats quartier de Kadıköy",
    shortDesc: "Le cœur branché de la rive asiatique",
    tag: "Promenade",
    ville: "Istanbul",
    image: "/images/Jour 2/Kadikoy 1.webp",
    photos: [
      "/images/Jour 2/achats_photo_1.webp",
      "/images/Jour 2/Kadikoy 2.webp",
      "/images/Jour 2/Kadikoy 1.webp",
      "/images/Jour 2/Kadikoy 3.webp",
      "/images/Jour 2/Kadikoy 4.webp",
    ],
    audioTitle: "Kadıköy, l'âme asiatique d'Istanbul",
    audioDuration: "3 min 10 sec",
    audioSrc: "/audio/places/kadikoy.mp3",
    gps: "40.988750 , 29.027639",
    historyLabel:"Présentation",
    history:
      "Kadıköy est l'un des quartiers les plus vivants de la rive asiatique d'Istanbul. Son marché (çarşı) regorge de produits frais, d'épices, de poissons et de boutiques locales. C'est un lieu de rencontre authentique, loin du tourisme de masse.",
    anecdotes: [
      "Aperçu de la Tour de Léandre depuis le bateau vers Kadıköy.",
      "Kadıköy est réputé pour ses rues piétonnes et ses cafés branchés.",
      "Il faut emprunter le passage de la rue des parapluies : Piri Çavuş Sokak",
      "Le marché de Kadıköy est l'un des plus anciens de la ville",
      "C'est là que papa a acheté une paire de samba marron.",
    ],
  },
  {
    id: "croisiere-bosphore",
    jour: [2],
    name: "Croisière sur le Bosphore",
    shortDesc: "Entre deux continents, entre deux mondes",
    tag: "Promenade",
    ville: "Istanbul",
    image: "/images/Jour 2/croisiere_sur_le_bosphore_photo_1.webp",
    photos: [
      "/images/Jour 2/croisiere_sur_le_bosphore_photo_1.webp",
      "/images/Jour 2/croisiere bosphore 1.webp",
      "/images/Jour 2/croisiere bosphore 2.webp",
    ],
    audioTitle: "Le Bosphore, frontière liquide",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Croisiere_Bosphore.mp3",
    historyLabel:"Présentation",
    history:
      "La croisière sur le Bosphore est l'une des expériences incontournables d'Istanbul. Ce détroit reliant la mer Noire à la mer de Marmara sépare l'Europe de l'Asie et offre des vues spectaculaires sur les palais, les mosquées et les villas ottomanes qui bordent ses rives.",
    anecdotes: [
      "Le Bosphore mesure environ 32 km de long.",
      "On peut voir le palais de Dolmabahçe, le palais de Çırağan et le fort de Rumeli Hisarı depuis le bateau.",
      "Des dauphins sont parfois aperçus dans le détroit.",
    ],
  },
  {
    id: "saint-sauveur-chora",
    jour: [2],
    name: "Saint-Sauveur in Chora",
    shortDesc: "Un trésor de mosaïques byzantines",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 2/Sainte-sauveur in chora 1.webp",
    photos: [
      "/images/Jour 2/Sainte-sauveur in chora 1.webp",
      "/images/Jour 2/Sainte-sauveur in chora 2.webp",
      "/images/Jour 2/Sainte-sauveur in chora 3.webp",
    ],
    audioTitle: "Chora, la beauté cachée",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Sainte-Sauveur-Chora.mp3",
    gps: "41.0317,28.9497",
    history:
      "L'église Saint-Sauveur in Chora, aujourd'hui musée (Kariye), est célèbre pour ses mosaïques et fresques byzantines parmi les plus belles qui subsistent. Datant du XIVe siècle, ces œuvres illustrent des scènes de la vie du Christ et de la Vierge avec une finesse exceptionnelle.",
    anecdotes: [
      "'Chora' signifie 'hors les murs' en grec, car l'église se trouvait à l'origine en dehors des remparts de Constantinople.",
      "Les mosaïques ont été réalisées entre 1315 et 1321.",
      "Le lieu est souvent moins fréquenté que Sainte-Sophie, ce qui permet une visite plus sereine.",
    ],
    links: [
      {
        label: "Pour approfondir",
        url: "https://www.churchofchora.com/",
      },
    ],
  },
  {
    id: "balat",
    jour: [2], // à préciser selon votre programme
    name: "Quartier de Balat",
    shortDesc: "Ruelles colorées entre Corne d'Or et collines historiques",
    tag: "Promenade",
    ville: "Istanbul",
    image: "/images/Jour 2/Balat 1.webp",
    photos: [
      "/images/Jour 2/Balat 2.webp",
      "/images/Jour 2/Balat 1.webp",
      "/images/Jour 2/Balat 3.webp",
      "/images/Jour 2/Balat 4.webp",
      "/images/Jour 2/Balat 5.webp",
      "/images/Jour 2/Balat 6.webp",
    ],
    audioTitle: "Balat, les couleurs du vieil Istanbul",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Balat.mp3",
    gps: "41.0286,28.9489",
    historyLabel: "Présentation",
    history:
      "Balat est l'un des plus anciens quartiers d'Istanbul, longtemps habité par les communautés juive, grecque et arménienne de la ville. Ses maisons ottomanes aux façades colorées, restaurées ou patinées par le temps, s'étagent sur les collines qui dominent la Corne d'Or. Aujourd'hui, artistes et cafés branchés se mêlent aux habitants historiques, donnant au quartier une atmosphère unique entre authenticité populaire et renouveau créatif.",
    anecdotes: [
      "La rue Kürkçü Çeşmesi Sokak est célèbre pour ses façades peintes de couleurs vives, très photographiée.",
      "L'escalier coloré de Çorbacı Çeşmesi, dans le prolongement de Kiremit Caddesi, est un autre incontournable pour les photos.",
      "Balat a longtemps été le cœur de la communauté juive séfarade d'Istanbul, arrivée après l'expulsion d'Espagne en 1492.",
      "Le quartier a inspiré de nombreux tournages de films et séries turques grâce à son cachet architectural.",
    ],
  },
  {
    id: "croisiere-nocturne",
    jour: [2],
    name: "Croisière nocturne",
    shortDesc: "Istanbul illuminée depuis l'eau",
    tag: "Promenade",
    ville: "Istanbul",
    image: "/images/Jour 2/croisiere_de_nuit.webp",
    photos: [
      "/images/Jour 2/croisiere_de_nuit.webp",
      "/images/Jour 2/croisiere nocturne 2.webp",
    ],
    audioTitle: "Istanbul la nuit, du Bosphore",
    audioDuration: "2 min 30 sec",
    audioSrc: "/audio/places/Croisiere_Nocturne.mp3",
    historyLabel: "Présentation",
    history:
      "La croisière nocturne sur le Bosphore offre une perspective magique sur Istanbul. Les palais, les mosquées et les ponts illuminés se reflètent dans l'eau, créant une atmosphère féerique et romantique.",
    anecdotes: [
      "Le pont du Bosphore est illuminé de mille feux la nuit.",
      "Le palais de Dolmabahçe est particulièrement spectaculaire vu depuis l'eau à la tombée de la nuit.",
      "C'est une expérience incontournable pour les amoureux de la ville.",
    ],
  },
  {
    id: "restaurant-vina-garden",
    reservationDocumentIds: ["restaurant-vina-garden"],
    jour: [2],
    name: "La Vina Garden 1864 Restaurant",
    shortDesc: "Une table à réserver à Sultanahmet",
    tag: "Restaurant",
    ville: "Istanbul",
    image: "/images/Jour 2/Vina Garden 1.webp",
    photos: [
      "/images/Jour 2/Vina Garden 1.webp",
      "/images/Jour 2/Vina Garden 2.webp",
      "/images/Jour 2/Vina Garden 3.webp",
    ],
    audioTitle: "Gastronomie à Sultanahmet",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Vina_Garden.mp3",
    gps: "41.0040927,28.9787788",
    historyLabel:"Présentation du restaurant",
    history:
      "Situé dans le quartier historique de Sultanahmet, La Vina Garden 1864 propose une cuisine raffinée dans un cadre élégant. C'est une adresse à réserver pour profiter d'un dîner de qualité au cœur de la vieille ville.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Réservation confirmée à 19h30/20h.",
      "Situé à Sultanahmet, à proximité des principaux monuments.",
      "Le restaurant propose une carte mêlant cuisine turque traditionnelle et créations modernes.",
      "Idéal pour aller ensuite se promener dans le quartier de Sultanahmet après le dîner.",
    ],
  },
    {
    id: "nuit-hotel-windsoer",
    reservationDocumentIds: ["hotel-istanbul-windsor"],
    jour: [2],
    name: "hôtel WINDSOR HOTEL & CONVENTION CENTER 5*",
    shortDesc: "Nuit à l'hôtel Windsor",
    tag: "Hôtel",
    ville: "Istanbul",
    image: "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
    photos: [
      "/images/Jour 2/windsor 1.webp",
      "/images/Jour 2/windsor 2.webp",
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 2.webp",
    ],
    gps: "41.044255,28.9131665",
    historyLabel:"Présentation de l'hôtel",
    history:
      "Le Windsor Hotel & Convention Center est un établissement 5★ moderne situé dans le quartier de Bayrampaşa, à Istanbul. Il se distingue par son vaste centre de convention, ses chambres élégantes et ses installations haut de gamme : spa complet, piscines intérieure et extérieure, sauna, hammam, ainsi qu’un salon panoramique au 17ᵉ étage offrant une vue superbe sur la ville et la Corne d’Or.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "1 chambre double et 1 chambre triple normalement réservées",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.windsorhotelistanbul.com/",
      },
    ],
  },
  {
    id: "topkapi",
    jour: [3],
    name: "Palais de Topkapi",
    shortDesc: "Le cœur du pouvoir des sultans ottomans pendant près de quatre siècles",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 3/Topkapi/Topkapi 2.webp",
    photos: [
      "/images/Jour 3/topkapi_photo_1.webp",
      "/images/Jour 3/topkapi_photo_2.webp",
      "/images/Jour 3/Topkapi/Topkapi 0.webp",
      "/images/Jour 3/Topkapi/Topkapi 1.webp",
      "/images/Jour 3/Topkapi/Topkapi 2.webp",
      "/images/Jour 3/Topkapi/Topkapi 3.webp",
      "/images/Jour 3/Topkapi/Topkapi 4.webp",
    ],
    audioTitle: "Découvrez le Palais de Topkapi",
    audioDuration: "4 min 20 sec",
    audioSrc: "/audio/places/Le_palais_de_Topkapi.mp3",
    gps: "41.0115,28.9834",
    history:
      "Construit à partir de 1459 sur les ordres du sultan Mehmed II, peu après la conquête de Constantinople, le Palais de Topkapi fut la résidence officielle des sultans ottomans et le centre administratif de l'Empire pendant près de quatre siècles. Véritable ville dans la ville, il abritait les appartements impériaux, le harem, les cuisines, le trésor et les salles où étaient prises les décisions qui influençaient une grande partie du monde méditerranéen et du Moyen-Orient.",
    anecdotes: [
      "Le palais compte quatre grandes cours successives, chacune plus privée que la précédente.",
      "Le Harem impérial pouvait accueillir plusieurs centaines de personnes, dont la famille du sultan et ses serviteurs.",
      "Le Trésor de Topkapi expose le célèbre poignard de Topkapi ainsi que le diamant du fabricant de cuillères, l'un des plus grands diamants exposés au monde.",
      "Depuis les terrasses du palais, la vue sur le Bosphore, la Corne d'Or et la mer de Marmara est spectaculaire.",
      "Le palais conserve plusieurs reliques sacrées de l'islam, notamment des objets traditionnellement attribués au prophète Mahomet.",
    ],
  },
  {
    id: "mosquee-bleue",
    jour: [3],
    name: "Mosquée Bleue",
    shortDesc: "La mosquée aux six minarets et 21 403 faïences",
    ville: "Istanbul",
    tag: "Visite",
    image: "/images/Jour 3/Mosquee bleue 3.webp",
    photos: [
      "/images/Jour 3/Mosquee bleue 3.webp",
      "/images/Jour 3/Mosquee bleue 2.webp",
      "/images/Jour 3/Mosqueebleue1.webp",
      "/images/Jour 3/Mosqueebleue2.webp",
      "/images/Jour 3/Mosqueebleue3.webp",
    ],
    audioTitle: "La Mosquée Bleue, merveille ottomane",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Mosquee_Bleue.mp3",
    gps: "41.0055,28.9768",
    history:
      "Construite au XVIIe siècle sous le sultan Ahmet Ier, la Mosquée Bleue (Sultanahmet Camii) est l'un des monuments les plus célèbres d'Istanbul. Elle doit son surnom aux 21 403 faïences bleues d'Iznik qui ornent son intérieur. Ses six minarets en font une mosquée unique à l'époque de sa construction.",
    anecdotes: [
      "Elle compte 21 403 faïences bleues d'Iznik.",
      "Ses six minarets ont provoqué un scandale à l'époque, car seule la mosquée de La Mecque en possédait autant.",
      "Le sultan Ahmet Ier a dû financer une septième minareth à La Mecque pour apaiser les critiques.",
    ],
  },
  {
    id: "hippodrome-byzantin",
    jour: [3],
    name: "Hippodrome byzantin",
    shortDesc: "Le cœur antique de Constantinople",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 3/Hippodrome 1.webp",
    photos: [
      "/images/Jour 3/Hippodrome 1.webp",
    ],
    audioTitle: "L'Hippodrome, théâtre de l'Empire",
    audioDuration: "3 min 00 sec",
    audioSrc: "/audio/places/Hippodrome_Byzantin.mp3",
    gps: "41.0065,28.9770",
    history:
      "L'Hippodrome de Constantinople était le centre de la vie publique de la ville byzantine. C'est ici que se déroulaient les courses de chars et les cérémonies impériales. Aujourd'hui, la place conserve trois obélisques antiques qui témoignent de son prestigieux passé.",
    anecdotes: [
      "L'obélisque de Théodose date de l'Égypte antique (XVe siècle av. J.-C.) et fut érigé ici en 390.",
      "La colonne serpentine fut rapportée de Delphes par Constantin.",
      "L'hippodrome pouvait accueillir jusqu'à 100 000 spectateurs.",
    ],
  },
  {
    id: "place-taksim",
    jour: [3],
    name: "Place Taksim",
    shortDesc: "Le cœur battant de l'Istanbul moderne",
    ville: "Istanbul",
    tag: "Promenade",
    image: "/images/Jour 3/Taksim 1.webp",
    photos: [
      "/images/Jour 3/Taksim 1.webp",
      "/images/Jour 3/Taksim 2.webp",
    ],
    audioTitle: "Taksim, carrefour de la vie stambouliote",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/places/Place_Taksim.mp3",
    gps: "41.0369,28.9850",
    history:
      "La place de Taksim est le centre névralgique de l'Istanbul moderne. Entourée de commerces, d'hôtels et de restaurants, elle est le point de départ de l'avenue Istiklal et un lieu de rassemblement pour les Stambouliotes.",
    anecdotes: [
      "Le Monument de la République au centre de la place date de 1928.",
      "Taksim signifie 'distribution' en turc, car c'est ici que l'eau était distribuée à la ville.",
      "C'est le point de départ de l'avenue Istiklal, artère commerçante de 1,4 km.",
    ],
  },
  {
    id: "pera-tour",
    jour: [3],
    name: "Quartier de Péra",
    shortDesc: "L'élégance d'antan au cœur de Beyoğlu",
    ville: "Istanbul",
    tag: "Promenade",
    image: "/images/Jour 3/pera_photo_1.webp",
    photos: [
      "/images/Jour 3/pera_photo_1.webp",
      "/images/Jour 3/Pera Galata 1.webp",
      "/images/Jour 3/Pera Galata 2.webp",
    ],
    audioTitle: "Péra, l'âme cosmopolite d'Istanbul",
    audioDuration: "3 min 40 sec",
    audioSrc: "/audio/places/Quartier_de_Pera.mp3",
    history:
      "Au début du XXe siècle, le quartier de Péra (aujourd'hui Beyoğlu) était la fierté de la ville. Ambassades, prestigieuses écoles, immeubles bourgeois, théâtres, cinémas, restaurants et tavernes s'y côtoiaient. C'est ici que la société élite stambouliote fréquentait. La Tour Galata, vestige médiéval, domine le quartier de ses 67 mètres.",
    anecdotes: [
      "Au début du XXe siècle, ce quartier était la fierté de la ville.",
      "Ambassades, prestigieuses écoles, immeubles bourgeois, théâtres, cinémas, restaurants et tavernes, c'est ici que la société élite stambouliote fréquentait.",
    ],
  },
  {
    id: "tour-galata",
    jour: [3],
    name: "Tour de Galata",
    shortDesc: "Un emblème médiéval dominant Istanbul depuis près de 700 ans",
    tag: "Promenade",
    ville: "Istanbul",
    image: "/images/Jour 3/Tour Galata 1.webp",
    photos: [
      "/images/Jour 3/Tour Galata 1.webp",
      "/images/Jour 3/Tour Galata 2.webp",
    ],
    audioTitle: "La Tour de Galata, sentinelle d'Istanbul",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Tour_Galata.mp3",
    gps: "41.0256,28.9741",
    history:
      "Construite en 1348 par les Génois installés dans le quartier de Galata, la Tour de Galata est l'un des monuments les plus emblématiques d'Istanbul. Haute de près de 67 mètres, elle servait autrefois de tour de défense et de surveillance sur les remparts de la colonie génoise. Transformée au fil des siècles en prison, observatoire puis point de départ des premières expériences aériennes d'Hezarfen Ahmed Çelebi, elle offre aujourd'hui l'un des plus beaux panoramas sur le Bosphore, la Corne d'Or, la vieille ville et les collines d'Istanbul.",
    anecdotes: [
      "Construite en 1348 par les Génois, la Tour de Galata est l'un des plus anciens monuments médiévaux encore visibles à Istanbul.",
      "Selon la légende, au XVIIe siècle, Hezarfen Ahmed Çelebi se serait élancé depuis la tour avec des ailes artificielles pour traverser le Bosphore en volant.",
      "Son sommet offre une vue spectaculaire à 360 degrés sur Sainte-Sophie, la Mosquée Bleue, le Palais de Topkapi et le détroit du Bosphore.",
    ],
  },
  {
    id: "restaurant-tershane",
    reservationDocumentIds: ["restaurant-tershane"],
    jour: [3],
    name: "Tershane",
    shortDesc: "Une table Bib Gourmand avec vue sur Istanbul",
    tag: "Restaurant",
    image: "/images/Jour 3/Tershane photo 1.webp",
    photos: [
      "/images/Jour 3/Tershane photo 1.webp",
      "/images/Jour 3/Tershane photo 2.webp",
      "/images/Jour 3/Tershane photo 3.webp",
    ],
    gps: "41.0246,28.9742",
    historyLabel: "Présentation du restaurant",
    history:
      "Installé au huitième étage de l'Hotel Momento, dans le quartier animé de Karaköy, Tershane propose une cuisine turque contemporaine dans un cadre élégant avec une belle vue sur les toits et les monuments historiques d'Istanbul. Le restaurant est distingué par un Bib Gourmand du Guide Michelin, récompensant une cuisine de qualité à prix raisonnable. La carte met notamment à l'honneur les mezzés, les kebabs et les grillades d'agneau, avec des préparations généreuses et parfumées.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Restaurant distingué par un Bib Gourmand du Guide Michelin.",
      "Réservation prévue à 20 h 00.",
      "Situé au 8e étage de l'Hotel Momento, dans le quartier de Karaköy.",
      "La terrasse du 9e étage offre une vue particulièrement intéressante sur les toits d'Istanbul.",
      "La carte fait notamment la part belle aux mezzés, kebabs et grillades d'agneau.",
      "Adresse : Tersane Caddesi No:24, Hotel Momento, Karaköy, Istanbul.",
    ],
  },
  {
    id: "restaurant-muutto-anatolian-tapas",
    reservationDocumentIds: ["restaurant-muutto-anatolian-tapas"],
    jour: [3],
    name: "Muutto Anatolian Tapas Bar",
    shortDesc: "La cuisine anatolienne revisitée façon tapas à Galataport",
    tag: "Restaurant",
    image: "/images/Jour 3/Muutto.webp",
    photos: [
      "/images/Jour 3/Muutto.webp",
      "/images/Jour 3/Muutto 1.webp",
      "/images/Jour 3/Muutto 2.webp",
      "/images/Jour 3/Muutto 3.webp"
    ],
    gps: "41.0278,28.9834",
    historyLabel: "Présentation du restaurant",
    history:
      "Installé au cœur de Galataport, sur les rives du Bosphore, Muutto Anatolian Tapas Bar propose une interprétation moderne et conviviale de la cuisine anatolienne. Le principe consiste à partager plusieurs assiettes inspirées des différentes régions de Turquie. Fromages anatoliens, mezzés, poissons, viandes et légumes sont revisités dans un esprit tapas, permettant de goûter plusieurs saveurs au cours du même repas.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Réservation confirmée à 21 h 00.",
      "Restaurant situé à Galataport, sur le front de mer de Karaköy.",
      "Le restaurant propose une cuisine anatolienne pensée autour du partage.",
      "La carte comprend notamment des mezzés, poissons, viandes et assiettes végétariennes.",
      "Une adresse particulièrement adaptée pour découvrir plusieurs spécialités au cours d'un même repas.",
      "La réservation a été faite et confirmée par Yahoo.",
    ],
  },
  {
    id: "nuit-hotel-windsoer-2",
    reservationDocumentIds: ["hotel-istanbul-windsor"],
    jour: [3],
    name: "hôtel WINDSOR HOTEL & CONVENTION CENTER 5*",
    shortDesc: "Nuit à l'hôtel Windsor",
    tag: "Hôtel",
    ville: "Istanbul",
    image: "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
    photos: [
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 2.webp",
    ],
    gps: "41.044255,28.9131665",
    historyLabel:"Présentation de l'hôtel",
    history:
      "Le Windsor Hotel & Convention Center est un établissement 5★ moderne situé dans le quartier de Bayrampaşa, à Istanbul. Il se distingue par son vaste centre de convention, ses chambres élégantes et ses installations haut de gamme : spa complet, piscines intérieure et extérieure, sauna, hammam, ainsi qu’un salon panoramique au 17ᵉ étage offrant une vue superbe sur la ville et la Corne d’Or.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "1 chambre double et 1 chambre triple normalement réservées",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.windsorhotelistanbul.com/",
      },
    ],
  },
  {
    id: "grand-bazar",
    jour: [4],
    name: "Grand Bazar",
    shortDesc: "Le plus célèbre marché couvert d'Istanbul",
    tag: "Visite",
    ville: "Istanbul",
    image: "/images/Jour 4/bazaar_photo_1.webp",
    photos: [
      "/images/Jour 4/bazaar_photo_1.webp",
      "images/Jour 4/Grand bazar 2.webp",
      "/images/Jour 4/Grand_bazar 1.webp",
      "/images/Jour 4/Grand_bazar 2.webp",
      "/images/Jour 4/Grand_bazar 3.webp",
      "/images/Jour 4/Grand Bazar Istanbul petit cours.webp",
      "/images/Jour 4/Grand Bazar Istanbul.webp",
      "/images/Jour 4/Grand Bazar Istanbul 2.webp",
      "/images/Jour 4/Grand Bazar Istanbul 3.webp",
      "/images/Jour 4/Grand Bazar Istanbul 4.webp",
      "/images/Jour 4/Grand Bazar Istanbul 5.webp"
    ],
    audioTitle: "Le Grand Bazar, un labyrinthe de trésors",
    audioDuration: "3 min 45 sec",
    audioSrc: "/audio/places/Grand_Bazar.mp3",
    gps: "41.0107,28.9680",
    history:
      "Fondé peu après la conquête de Constantinople par le sultan Mehmed II en 1455, le Grand Bazar est l'un des plus anciens et des plus vastes marchés couverts du monde. Au fil des siècles, il est devenu un véritable centre du commerce reliant l'Europe et l'Asie. Aujourd'hui, ses 61 rues couvertes abritent plus de 4 000 boutiques proposant tapis, bijoux, céramiques, épices, cuir, lampes, textiles et souvenirs. Malgré les incendies et les séismes qu'il a traversés au cours de son histoire, le Grand Bazar a conservé son atmosphère unique, où se mêlent patrimoine, artisanat et animation permanente.",
    links: [
      {
        label: "Ouvrir la carte interactive de Zincirli Han",
        url: "/visites-guidees/carte_zincirli_han.html",
      },
    ],
    anecdotes: [
      "Le Grand Bazar accueille entre 250 000 et 400 000 visiteurs chaque jour, ce qui en fait l'un des marchés les plus fréquentés au monde.",
      "Avec plus de 4 000 boutiques réparties sur 61 rues couvertes, il ressemble à une véritable ville dans la ville.",
      "La tradition de la négociation est toujours bien vivante : marchander fait partie intégrante de l'expérience d'achat.",
      "Dans Skyfall, James Bond fait une course-poursuite à moto sur les toits du grand bazar d’Istanbul.",
    ],
  },
  {
    id: "bus-istanbul-ankara",
    jour: [4], // à préciser selon ton programme
    name: "Trajet en bus Istanbul – Ankara",
    shortDesc: "Traversée de l'Anatolie, entre deux capitales",
    tag: "Trajet",
    ville: "Istanbul",
    image: "/images/Bus.webp",
    photos: [
      "/images/Bus.webp",
      "/images/Jour 4/Trajet Istanbul - Ankara.webp",
    ],
    audioTitle: "Sur la route d'Ankara, à travers l'Anatolie",
    audioDuration: "1 min 05 sec",
    audioSrc: "/audio/places/Trajet_Istanbul - ankara.mp3",
    links: [
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/istanbul_ankara_bus_route.html",
      },
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/Istanbul,+Turquie/Ankara,+Turquie/@40.373303,28.978798,7z/data=!4m14!4m13!1m5!1m1!1s0x14caa2f3e6b8e9d3:0x400bd2ce5a1f0c0!2m2!1d28.9783589!2d41.0082376!1m5!1m1!1s0x14caa2f3e6b8e9d3:0x400bd2ce5a1f0c0!2m2!1d32.8597419!2d39.9333655",
      },
    ],
    historyLabel:"Le trajet en bus Istanbul – Ankara",
    history:
      "Le trajet en bus entre Istanbul et Ankara couvre environ 450 km et dure généralement 5 à 6 heures. La route quitte les rives du Bosphore pour traverser les plaines et collines de l'Anatolie occidentale, offrant un aperçu de la Turquie rurale, loin de l'agitation des grandes villes. Les compagnies turques (Metro, Kâmil Koç, Pamukkale...) sont réputées pour leur confort et leur ponctualité, avec des bus modernes équipés de sièges inclinables et de services à bord. Les montagnes de Bolu — après avoir quitté la région de Sakarya, le bus grimpe dans les montagnes de Bolu, avec des forêts de conifères, des vallées verdoyantes et des routes sinueuses. En automne, les feuillages flamboyants offrent un spectacle magnifique, et en hiver, les paysages se couvrent de neige",
    anecdotes: [
      "La route traverse le plateau anatolien, un paysage de collines douces et de steppes qui change radicalement du décor côtier d'Istanbul.",
      "Ankara, contrairement à Istanbul, est une ville plus administrative et moderne : le contraste est saisissant à l'arrivée.",
    ],
  },
  {
    id: "ankara",
    jour: [4],
    name: "Ankara",
    shortDesc: "La capitale moderne au cœur de la Turquie",
    tag: "Ville",
    ville: "Ankara",
    image: "/images/Jour 4/Ankara 1.webp",
    photos: [
      "/images/Jour 4/ankara_photo_1.webp",
      "/images/Jour 4/ankara_photo_2.webp",
      "/images/Jour 4/Ankara 1.webp",
      "/images/Jour 4/Ankara 2.webp",
      "/images/Jour 4/Ankara 3.webp",
      "/images/Jour 4/Ankara 4.webp",
    ],
    audioTitle: "Ankara, le cœur politique de la Turquie",
    audioDuration: "3 min 40 sec",
    audioSrc: "/audio/places/Ankara.mp3",
    gps: "39.9208,32.8541",
    history:
      "Située au cœur du plateau anatolien, Ankara est la capitale de la République de Turquie depuis 1923. Si son histoire remonte à l'Antiquité, avec les Hittites, les Phrygiens, les Romains et les Byzantins, c'est sous l'impulsion de Mustafa Kemal Atatürk qu'elle prend une dimension nationale. Choisie pour sa position centrale et stratégique, Ankara remplace Istanbul comme capitale afin de symboliser la naissance d'une Turquie moderne, tournée vers l'avenir. Aujourd'hui, elle est le centre politique et administratif du pays, abritant le Parlement, les ministères, les ambassades et le mausolée d'Atatürk, tout en conservant un riche patrimoine historique dominé par sa citadelle et les vestiges des civilisations qui s'y sont succédé.",
    anecdotes: [
      "Ankara est devenue la capitale de la Turquie le 13 octobre 1923, quelques semaines avant la proclamation officielle de la République.",
      "Le mausolée d'Atatürk, Anıtkabir, est l'un des monuments les plus visités du pays et accueille plusieurs millions de visiteurs chaque année.",
      "Bien qu'Istanbul soit la plus grande ville de Turquie, Ankara concentre les principales institutions politiques et diplomatiques du pays.",
    ],
  },
  {
    id: "nuit-HILTONSA-ANKARA",
    reservationDocumentIds: ["hotel-ankara-hiltonsa"],
    jour: [4],
    name: "hôtel HILTONSA ANKARA 5*",
    shortDesc: "Diner et nuit à l'hôtel HILTONSA ANKARA",
    tag: "Hôtel",
    ville: "Ankara",
    image: "/images/Jour 4/Nuit hotel jour 3 - 1.webp",
    photos: [
      "/images/Jour 4/hotels_Ankara.webp",
      "/images/Jour 4/Nuit hotel jour 3 - 1.webp",
      "/images/Jour 4/Nuit hotel jour 3 - 2.webp",
    ],
    gps: "39.9019688 , 32.8638103",
    historyLabel:"Présentation de l'hôtel",
    history:
      "Le HiltonSA Ankara est un hôtel 5★ emblématique situé dans le quartier diplomatique de Çankaya, l’un des plus prestigieux d’Ankara. Installé dans une tour moderne, il propose des chambres élégantes, un restaurant avec terrasse, un piano‑bar, ainsi qu’un centre de bien‑être complet comprenant piscine intérieure, sauna et salle de sport.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "1 chambre double et 1 chambre triple normalement réservées",
      "Restaurant réservé pour le dîner du soir à l'hôtel",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.hilton.com/en/hotels/ankhitw-ankara-hiltonsa/",
      },
    ],
  },
   {
    id: "anitkabir",
    jour: [5],
    name: "Mausolée d'Atatürk",
    shortDesc: "Le monument national de la République turque",
    tag: "Visite",
    ville: "Ankara",
    image: "/images/Jour 5/Anitkabir_1.webp",
    photos: [
      "/images/Jour 5/Anitkabir_1.webp",
      "/images/Jour 5/Anitkabir_2.webp",
      "/images/Jour 5/Anitkabir_3.webp"
      ],
    audioTitle: "Anitkabir, la mémoire d'une nation",
    audioDuration: "3 min 50 sec",
    audioSrc: "/audio/places/Mausolee_d_Ataturk.mp3",
    history: "Anıtkabir est le mausolée de Mustafa Kemal Atatürk, fondateur et premier président de la République de Turquie. Situé à Ankara sur la colline d'Anıttepe, ce monument monumental fut construit entre 1944 et 1953. Le complexe de 750 000 m² comprend le mausolée, le Parc de la Paix, l'allée des Lions et plusieurs tours symboliques. Les pierres et marbres proviennent de toutes les régions de Turquie, symbolisant l'unité nationale. C'est un lieu de pèlerinage où des millions de visiteurs viennent chaque année rendre hommage au Père de la Nation.",
    anecdotes: [
      "Le drapeau turque flotte sur un mât de 33,53 m, le plus haut mât d'un seul tenant d'Europe.",
      "Les soldats de la garde d'honneur sont sélectionnés pour leur taille (minimum 1m80) et leur allure impeccable.",
      "Le sarcophage d'Atatürk pèse 40 tonnes et est fait d'un seul bloc de pierre."
    ]
  },
  {
  id: "trajet-ankara-cappadoce",
  jour: [5],
  name: "D'Ankara à la Cappadoce",
  shortDesc: "En route vers les paysages les plus étonnants de Turquie",
  tag: "Trajet",
  ville: "Ankara",
  image: "/images/Bus.webp",
  photos: [
    "/images/Jour 5/chemin vers Cappadoce 1.webp",
    "/images/Jour 5/chemin vers Cappadoce 2.webp",
    "/images/Jour 5/chemin vers Cappadoce 3.webp",
    "/images/Jour 5/chemin vers Cappadoce 4.webp",
    "/images/Jour 5/chemin vers Cappadoce 5.webp",
    "/images/Jour 5/chemin vers Cappadoce 6.webp",  
  ],
  audioTitle: "Sur la route de la Cappadoce",
  audioDuration: "3 min 30 sec",
  audioSrc: "/audio/places/Ankara-vers-Cappadoce.mp3",
  historyLabel: "Le trajet",
  history:
    "En quittant Ankara, la capitale moderne de la Turquie, la route s'enfonce progressivement dans les vastes plateaux d'Anatolie centrale. Les immeubles laissent place aux champs de céréales, aux collines ondulantes et aux immenses étendues où l'on croise parfois des troupeaux de moutons ou quelques villages traditionnels. Après environ trois heures de route, le paysage commence à changer. Les premières formations rocheuses apparaissent, sculptées par des millions d'années d'érosion volcanique. Vous entrez alors dans l'une des régions géologiques les plus fascinantes au monde : la Cappadoce.",
  anecdotesLabel: "À observer pendant le trajet",
  anecdotes: [
    "La distance entre Ankara et la Cappadoce est d'environ 290 kilomètres.",
    "Le trajet dure généralement entre 3 h et 3 h 30 selon les arrêts.",
    "Vous traversez le cœur de l'Anatolie, vaste région agricole de la Turquie.",
    "Les paysages deviennent progressivement plus minéraux à l'approche de la Cappadoce.",
    "Les premières cheminées de fées annoncent que vous êtes arrivé dans un décor presque irréel.",
  ],
  likns: [
    {
      label: "Ouvrir la carte interactive du trajet via google maps",
      url: "https://www.google.com/maps/dir/Ankara,+Turquie/Cappadoce,+Turquie/@39.9208,32.8541,7z/data=!4m14!4m13!1m5!1m1!1s0x14d34f3e6c9b0e7f:0x400bd2ce2b6a0c0!2m2!1d32.8541!2d39.9208!1m5!1m1!1s0x14d3f3e6c9b0e7f:0x400bd2ce2b6a0c0!2m2!1d34.8279!2d38.6439",
    },
  ],
  links: [
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/ankara_burcu_kaya_route.html",
      },
    ],
  },
  {
    id: "lac-sale",
    jour: [5],
    name: "Lac salé (Tuz Gölü)",
    shortDesc: "Une étendue salée scintillante au cœur de l'Anatolie",
    tag: "Découvrir",
    ville: "Cappadoce",
    image: "/images/Jour 5/Lac_Sale_1.webp",
    photos: [
      "/images/Jour 5/Lac_Sale_1.webp",
      "/images/Jour 5/Lac_Sale_2.webp",
      "/images/Jour 5/Lac_Sale_3.webp",
      "/images/Jour 5/Lac_Sale_4.webp",
      "/images/Jour 5/Lac_Sale_5.webp",
      "/images/Jour 5/Lac_Sale_6.webp",
    ],
    audioTitle: "Le lac salé de Turquie",
    audioDuration: "2 min 30 sec",
    audioSrc: "/audio/places/lac_sale.mp3",
    gps: "38.7626,33.3649",
    history: "Le lac Tuz est l'un des plus grands lacs salés de Turquie. Situé au cœur de l'Anatolie centrale, il s'étend sur plus de 1 600 km². Ses eaux peu profondes reflètent le ciel comme un miroir, créant un paysage surréaliste particulièrement spectaculaire en saison sèche lorsque le sel cristallise à la surface.",
    anecdotes: [
      "Le lac Tuz fournit près de 70 % du sel consommé en Turquie.",
      "En été, l'évaporation intense crée une croûte de sel blanche d'une épaisseur impressionnante.",
      "Certaines zones du lac deviennent rose en raison d'algues halophiles qui prospèrent dans l'eau salée.",
    ],
  },
  {
    id: "ville-souterraine",
    jour: [5],
    name: "Ville souterraine byzantine",
    shortDesc: "Refuge souterrain creusé dans la roche volcanique",
    tag: "Visite",
    ville: "Cappadoce",
    image: "/images/Jour 5/Ville_souterraine_1.webp",
    photos: [
      "images/Jour 5/ville_souterraine_photo_1.webp",
      "/images/Jour 5/Ville_souterraine_1.webp",
      "/images/Jour 5/Ville_souterraine_2.webp",
      "/images/Jour 5/Ville_souterraine_3.webp",
      "/images/Jour 5/Ville_souterraine_4.webp",
      "/images/Jour 5/Ville_souterraine_5.webp",
      "/images/Jour 5/Ville_souterraine_6.webp",
    ],
    audioTitle: "Les cités cachées de Cappadoce",
    audioDuration: "3 min 15 sec",
    audioSrc: "/audio/places/ville_souteraine_bizantine.mp3",
    history: "Creusées dans le tuf volcanique tendre de Cappadoce, ces villes souterraines servirent de refuge aux populations chrétiennes entre le VIIème et le Xème siècle. Derinkuyu et Kaymaklı sont les plus célèbres, pouvant abriter jusqu'à 20 000 personnes sur plusieurs niveaux avec leurs cuisines, églises, étables et systèmes de ventilation sophistiqués.",
    anecdotes: [
      "Certaines villes souterraines communiquent entre elles par des tunnels s'étendant sur plusieurs kilomètres.",
      "Les pierres roulantes massives servaient à bloquer les entrées en cas d'invasion.",
      "Les puits de ventilation étaient si bien conçus qu'ils empêchaient l'ennemi de détecter la présence des habitants.",
    ],
  },
    {
    id: "restaurant-happena",
    reservationDocumentIds: ["restaurant-happena"],
    jour: [5],
    name: "Happena Restaurant",
    shortDesc: "Un dîner aux saveurs de l'Anatolie ancienne à Göreme",
    tag: "Restaurant",
    image: "/images/Jour 5/Happena 1.webp",
    photos: [
      "/images/Jour 5/Happena 1.webp",
      "/images/Jour 5/Happena 2.webp",
      "/images/Jour 5/Happena 3.webp",
      "/images/Jour 5/Happena 4.webp",
    ],
    gps: "38.6424,34.8281",
    historyLabel: "Présentation du restaurant",
    history:
      "Au cœur de Göreme, Happena Restaurant propose une expérience culinaire inspirée des anciennes civilisations d'Anatolie, notamment des Hittites. Le restaurant cherche à faire revivre des saveurs et des traditions culinaires anciennes dans un cadre chaleureux, avec une belle vue sur les paysages de Cappadoce. L'expérience mêle ainsi gastronomie, histoire et découverte des traditions de cette région unique.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Réservation confirmée à 19 h 30.",
      "Réservation effectuée sur l'application OpenTable.",
      "Confirmation reçue à la fois dans l'application et par e-mail.",
      "Situé au No:1 Yavuz Sokak, au cœur de Göreme.",
      "Le restaurant propose une cuisine inspirée des Hittites et des anciennes civilisations anatoliennes.",
      "Le restaurant bénéficie d'une vue panoramique sur Göreme, particulièrement agréable en fin de journée.",
    ],
  },
  {
  id: "restaurant-kaira-rooftop",
  reservationDocumentIds: ["restaurant-kaira-rooftop"],
  jour: [5],
  name: "Kaira Rooftop Bar & Restaurant",
  shortDesc: "Un dîner avec vue sur les cheminées de fées",
  tag: "Restaurant",
  ville: "Cappadoce",
  image: "/images/Jour 5/Kaira Rooftop 1.webp",
  photos: [
    "/images/Jour 5/Kaira Rooftop 1.webp",
    "/images/Jour 5/Kaira Rooftop 2.webp",
    "/images/Jour 5/Kaira Rooftop 3.webp",
  ],
  gps: "38.6439,34.8283",
  historyLabel: "Présentation du restaurant",
  history:
    "Situé au cœur de Göreme, le Kaira Rooftop Bar & Restaurant offre l'une des plus belles vues sur les célèbres cheminées de fées de Cappadoce. Depuis sa terrasse panoramique, les visiteurs profitent d'un cadre exceptionnel, particulièrement au coucher du soleil, tout en dégustant une cuisine turque généreuse accompagnée de quelques spécialités internationales. L'atmosphère est à la fois élégante, chaleureuse et propice à un dîner mémorable après une journée d'exploration dans les vallées de Cappadoce.",
  anecdotesLabel: "Informations pratiques",
  anecdotes: [
    "ATTENTION : réservation non faite, venir vers 18h30/19h00 pour avoir une table pour 5 avec vue sur couché du soleil.",
    "Terrasse panoramique offrant une vue spectaculaire sur Göreme et les cheminées de fées.",
    "Le coucher du soleil est le moment le plus prisé",
    "Cuisine turque traditionnelle, grillades, mezzés et quelques plats internationaux.",
    "Situé à quelques minutes à pied du centre de Göreme, il est facilement accessible après une balade dans le village.",
  ],
},
{
  id: "restaurant-sky-rooftop",
  reservationDocumentIds: ["restaurant-sky-rooftop"],
  jour: [5],
  name: "Sky Cappadocia Rooftop & Restaurant",
  shortDesc: "Une vue imprenable sur Göreme au coucher du soleil",
  tag: "Restaurant",
  ville: "Cappadoce",
  image: "/images/Jour 5/Sky rooftop restaurant 1.webp",
  photos: [
    "/images/Jour 5/Sky rooftop restaurant 1.webp",
    "/images/Jour 5/Sky rooftop restaurant 2.webp",
    "/images/Jour 5/Sky rooftop restaurant 3.webp",
  ],
  gps: "38.6437,34.8277",
  historyLabel: "Présentation du restaurant",
  history:
    "Perché sur les hauteurs de Göreme, le Sky Cappadocia Rooftop & Restaurant offre une vue panoramique exceptionnelle sur les vallées et les célèbres cheminées de fées. Sa terrasse est particulièrement appréciée au moment du coucher du soleil, lorsque les falaises volcaniques se parent de teintes dorées. La carte met à l'honneur les saveurs de la cuisine turque, accompagnées d'une belle sélection de vins et de cocktails, dans une ambiance élégante et décontractée.",
  anecdotesLabel: "Informations pratiques",
  anecdotes: [
    "Pas de réservation faite, il faudra se rendre sur place",
    "L'un des meilleurs endroits de Göreme pour admirer le coucher du soleil.",
    "Terrasse avec vue panoramique sur les vallées et les habitations troglodytiques.",
    "Cuisine turque, mezzés, grillades et cocktails servis dans une ambiance lounge.",
    "Il est conseillé de réserver une table en terrasse, particulièrement entre avril et octobre.",
  ],
},
{
    id: "nuit-BURCU-KAYA-CAPPADOCE",
  reservationDocumentIds: ["hotel-cappadoce-burcu-kaya"],
    jour: [5],
    name: "hôtel BURCU KAYA - CAPPADOCE 4*",
    shortDesc: "Nuit (et diner?) à l'hôtel BURCU KAYA - CAPPADOCE",
    tag: "Hôtel",
    ville: "Cappadoce",
    image: "/images/Jour 5/Nuit hotel jour 5 - 1.webp",
    photos: [
      "/images/Jour 5/hotels_Cappadoce.webp",
      "/images/Jour 5/Nuit hotel jour 5 - 1.webp",
      "/images/Jour 5/Nuit hotel jour 5 - 2.webp",
    ],
    gps: "38.642980 , 34.853410",
    historyLabel:"Présentation de l'hôtel",
    history:
      "Le Burcu Kaya Hotel est un établissement 4★ typique de la Cappadoce, construit dans le style troglodyte avec des façades en pierre locale. Il se trouve dans un secteur calme d’Ortahisar, à proximité du château et à quelques minutes des vallées emblématiques (Rose Valley, Red Valley, Love Valley).\n"+
      "L’hôtel propose des chambres creusées dans la roche, une piscine extérieure, un restaurant panoramique, ainsi qu’une atmosphère authentique idéale pour un séjour romantique ou une découverte culturelle.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "1 chambre double et 1 chambre triple normalement réservées",
      "Restaurant réservé pour le dîner du soir à l'hôtel si nécessaire",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://burcukayahotel.com/",
      },
    ],
  },
  {
    id: "montgolfiere-cappadoce",
    reservationDocumentIds: [
      "Montgolfiere-rainbow-balloons",
      "Montgolfiere-discovery-balloons",
      "Montgolfiere-Nazar-balloons",
    ],
    jour: [6],
    name: "Vol en montgolfière",
    shortDesc: "Survoler les cheminées de fées au lever du jour",
    tag: "Montgolfière",
    ville: "Cappadoce",
    image: "/images/Jour 6/Montgolfiere_1.webp",
    photos: [
      "/images/Jour 6/Montgolfiere 1.webp",
      "/images/Jour 6/Montgolfiere 2.webp",
      "/images/Jour 6/Montgolfiere_1.webp",
      "/images/Jour 6/Montgolfiere_2.webp",
      "/images/Jour 6/Montgolfiere_4.webp"
    ],
    audioTitle: "Cappadoce vue du ciel",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/places/vol_en_montgolfiere.mp3",
    gps: "38.6431,34.8287",
    historyLabel: "Le vol en montgolfière",
    history: "Le vol en montgolfière au-dessus de Cappadoce est considéré comme l'une des plus belles expériences aériennes au monde. Chaque année, des centaines de ballons s'élèvent à l'aube pour offrir une vue panoramique sur les vallées, vignobles et cheminées de fées. Cette tradition a commencé dans les années 1990 et attire désormais des visiteurs du monde entier.",
    anecdotesLabel: "Présentation et conseils",
    anecdotes: [
      "Les vols ont lieu très tôt le matin pour profiter des vents les plus calmes.",
      "Prise en charge à l'hôtel à 4h du matin, horaire à confirmer",
      "On peut parfois apercevoir des renards et des lièvres depuis le ciel.",
      "La Cappadoce est l'un des sites de montgolfière les plus fréquentés au monde, aux côtés de Bagan et du Serengeti."
    ]
  },    {
    id: "cappadoce",
    jour: [6],
    name: "Cappadoce",
    shortDesc: "Un paysage lunaire aux cheminées de fées",
    tag: "Découvrir",
    ville: "Cappadoce",
    image: "/images/Jour 6/Cappadoce_1.webp",
    photos: [
      "/images/Jour 6/Cappadoce_1.webp",
      "/images/Jour 6/Cappadoce_2.webp",
      "/images/Jour 6/Cappadoce_3.webp",
      "/images/Jour 6/Cappadoce_4.webp",
      "/images/Jour 6/Cappadoce_5.webp",
      "/images/Jour 6/Cappadoce_6.webp",
      "/images/Jour 6/Cappadoce_7.webp"
    ],
    audioTitle: "Cappadoce, terre des fées",
    audioDuration: "4 min 10 sec",
    audioSrc: "/audio/places/CAPPADOCE et Goreme.mp3",
    gps: "38.6431,34.8287",
    history: "Cappadoce est une région unique au monde, façonnée par des millions d'années d'érosion volcanique. Berceau de la chrétienté primitive, elle abrita les premières communautés chrétiennes qui creusèrent églises et monastères dans la roche. Son paysage lunaire, parsemé de cheminées de fées coiffées de basalte, en fait l'un des sites naturels les plus spectaculaires de la planète.",
    anecdotes: [
      "Le mot 'Cappadoce' viendrait du vieux perse et signifierait 'le pays des beaux chevaux'.",
      "Les cheminées de fées sont formées lorsque le basalte dur protège le tuf tendre situé en dessous de l'érosion.",
      "Plus de 3 000 églises rupestres ont été recensées dans la région."
    ]
  },
  {
    id: "goreme",
    jour: [6],
    name: "Musée en plein air de Göreme",
    shortDesc: "Églises rupestres et fresques byzantines — UNESCO",
    tag: "Visite",
    ville: "Göreme",
    image: "/images/Jour 6/goreme_photo_1.webp",
    photos: [
      "/images/Jour 6/goreme_photo_1.webp",
      "/images/Jour 6/goreme_photo_2.webp",
      "/images/Jour 6/goreme_photo_3.webp",
      "/images/Jour 6/goreme_photo_4.webp",
      "/images/Jour 6/goreme_photo_5.webp",
      "/images/Jour 6/Goreme_1.webp",
      "/images/Jour 6/Goreme_2.webp",
      "/images/Jour 6/Goreme_4.webp",
      "/images/Jour 6/Goreme_6.webp",
      "/images/Jour 6/Goreme_7.webp"
    ],
    audioTitle: "Göreme, trésor de l'UNESCO",
    audioDuration: "3 min 45 sec",
    audioSrc: "/audio/places/Musee_en_pleine_air_de_Goreme.mp3",
    gps: "38.6413,34.8466",
    history: "Le musée en plein air de Göreme est un site classé au patrimoine mondial de l'UNESCO depuis 1985. Il regroupe plusieurs églises rupestres datant des IXème au XIème siècles, ornées de fresques byzantines remarquablement conservées. Ces sanctuaires taillés dans la roche témoignent de la richesse spirituelle et artistique des premières communautés chrétiennes d'Anatolie.",
    anecdotes: [
      "L'église de la Pomme (Elmali Kilise) doit son nom à une pomme peinte près de l'autel.",
      "Les fresques de l'église Sainte-Barbara sont parmi les plus anciennes du site.",
      "Le site servit de refuge aux moines byzantins qui y vécurent en ermitages."
    ]
  },
  {
    id: "vallees-cappadoce",
    jour: [6],
    name: "Vallées d'Avcilar et Güvercinlik",
    shortDesc: "Cheminées de fées aux formes étonnantes",
    tag: "Découvrir",
    ville: "Cappadoce",
    image: "/images/Jour 6/Vallée de Guvercinlik.webp",
    photos: [
      "/images/Jour 6/Vallée de Guvercinlik.webp",
      "/images/Jour 6/avcilar_photo_1.webp",
      "/images/Jour 6/Vallee_1.webp",
      "/images/Jour 6/Vallee_2.webp",
      "/images/Jour 6/Vallee_3.webp",
      "/images/Jour 6/Vallee_4.webp"
    ],
    audioTitle: "Les vallées merveilleuses",
    audioDuration: "2 min 20 sec",
    audioSrc: "/audio/places/Valles_avcilar_vercinlik.mp3",
    history: "Les vallées d'Avcilar (Vallée des Croyants) et de Güvercinlik (Vallée des Pigeons) offrent les panoramas les plus emblématiques de Cappadoce. Avcilar est célèbre pour ses formations rocheuses aux formes anthropomorphes, tandis que Güvercinlik doit son nom aux nombreux pigeons qui y nichent dans des pigeonniers creusés dans la falaise.",
    anecdotes: [
      "Les habitants collectaient la fiente de pigeon comme engrais naturel pour leurs vignes.",
      "Certaines cheminées de fées ressemblent étrangement à des silhouettes humaines ou animales.",
      "Les pigeonniers étaient peints de couleurs vives pour attirer les oiseaux."
    ]
  },
  {
    id: "derviche-tourneurs-spec",
    name: "Les derviches tourneurs",
    shortDesc: "La danse mystique soufie, poésie en mouvement vers l'infini",
    tag: "Activité",
    image:
      "/images/Culture/derviche_tourneur.webp",
    photos: [
      "/images/Culture/derviche_tourneur.webp",
    ],
    audioTitle: "La roue vers l'Absolu",
    audioDuration: "2 min 50 sec",
    audioSrc: "/audio/Culture/Les_derviches_tourneurs.mp3",
    historyLabel:"présentation",
    history:
      "La cérémonie des derviches tourneurs, ou Sema, est une pratique soufie née au XIIIe siècle sous l'impulsion de Jalal ad-Din Rumi, fondateur de l'ordre mevlevi à Konya. La danse n'est pas un spectacle mais une méditation active : le derviche, vêtu d'une longue jupe blanche symbolisant le linceul, tourne sur lui-même la tête inclinée et les bras ouverts — la main droite vers le ciel pour recevoir la grâce divine, la gauche vers la terre pour la transmettre. La rotation, toujours dans le sens inverse des aiguilles d'une montre, symbolise les planètes en orbite autour du soleil et l'âme tournant vers Dieu. Bien que l'ordre mevlevi ait été interdit en 1925 par Atatürk, la Sema a été réhabilitée comme patrimoine culturel immatériel de l'UNESCO en 2008 et se pratique aujourd'hui dans des cadres touristiques et spirituels, notamment à Konya et à Istanbul.",
    anecdotes: [
      "À Konya, lors du festival annuel de Mevlana en décembre, des milliers de derviches tournent simultanément dans la grande salle de la Mevlana Museum, créant un murmure de tissus blancs si hypnotique que certains spectateurs oublient de cligner des yeux pendant des minutes entières.",
      "Avant chaque cérémonie, les derviches retirent leurs manteaux noirs symbolisant le tombeau terrestre pour révéler leurs robes blanches — un passage de la mort à la résurrection spirituelle qui dure exactement le temps d'un soupir collectif dans la salle.",
    ],
  },
{
  id: "restaurant-nana-cappadocia",
  reservationDocumentIds: ["restaurant-nana-cappadocia"],
  jour: [6],
  name: "NANA Cappadocia Restaurant",
  shortDesc: "Un dîner en terrasse au cœur de Göreme",
  tag: "Restaurant",
  ville: "Cappadoce",
  image: "/images/Jour 6/NANA Cappadocia 1.webp",
  photos: [
    "/images/Jour 6/NANA Cappadocia 1.webp",
    "/images/Jour 6/NANA Cappadocia 2.webp",
    "/images/Jour 6/NANA Cappadocia 3.webp",
    "/images/Jour 6/Reservation Nana Cappadoce.webp"
  ],
  gps: "38.641846,34.829168",
  historyLabel: "Présentation du restaurant",
  history:
    "Situé au cœur de Göreme, NANA Cappadocia Restaurant séduit par sa terrasse offrant une vue sur le village et les paysages emblématiques de la Cappadoce. Dans une ambiance chaleureuse et élégante, le restaurant propose une cuisine turque mettant à l'honneur les spécialités locales, préparées avec des produits frais. C'est une adresse idéale pour terminer une journée d'exploration en profitant d'un dîner face aux reliefs uniques de la région.",
  anecdotesLabel: "Informations pratiques",
  anecdotes: [
    "Réservation confirmée via WhatsApp.",
    "Jeudi 21 août à 19 h 15.",
    "Table réservée en terrasse pour 5 personnes.",
    "Situé dans le quartier d'İsali - Gaferli, à quelques minutes à pied du centre de Göreme.",
    "Le restaurant est réputé pour son cadre agréable, particulièrement au coucher du soleil.",
  ],
  links: [
    {
        label: "Site du restaurant & bar",
        url: "https://nanacappadocia.com/gallery/",
      },
  ]
},
{
  id: "restaurant-numero-10-ortahisar",
  reservationDocumentIds: ["restaurant-numero-10-ortahisar"],
  jour: [6],
  name: "Restaurant N°10",
  shortDesc: "Une soirée conviviale au cœur d'Ortahisar",
  ville: "Cappadoce",
  tag: "Restaurant",
  image: "/images/Jour 6/no-10-restaurant 1.webp",
  photos: [
    "/images/Jour 6/no-10-restaurant 1.webp",
    "/images/Jour 6/no-10-restaurant 2.webp",
    "/images/Jour 6/no-10-restaurant 3.webp",
  ],
  gps: "38.6177,34.8719",
  historyLabel: "Présentation du restaurant",
  history:
    "Situé à Ortahisar, à proximité de l'hôtel, le Restaurant N°10 propose une expérience conviviale au cœur d'un des villages emblématiques de Cappadoce. Ortahisar est connu pour son imposante forteresse rocheuse qui domine la vallée et ses ruelles authentiques bordées de maisons traditionnelles. Après une journée de découverte des paysages cappadociens, ce restaurant offre une halte agréable pour profiter de la cuisine locale dans une ambiance chaleureuse.",

  anecdotesLabel: "Informations pratiques",
  anecdotes: [
    "Demande de réservation effectuée par SMS, confirmation en attente.",
    "Horaire souhaité : 19 h 15.",
    "Restaurant situé à proximité de l'hôtel, pratique pour une soirée sans déplacement.",
    "Adresse : Ulus Meydanı Kaledibi Sok. Ortahisar, Ürgüp, Nevşehir, Turquie.",
    "Ortahisar est célèbre pour sa grande forteresse naturelle creusée dans la roche volcanique.",
  ],
},
{
    id: "nuit-BURCU-KAYA-CAPPADOCE-2",
  reservationDocumentIds: ["hotel-cappadoce-burcu-kaya"],
    jour: [6],
    name: "hôtel BURCU KAYA - CAPPADOCE 4*",
    shortDesc: "Nuit (et diner?) à l'hôtel BURCU KAYA - CAPPADOCE",
    tag: "Hôtel",
    image: "/images/Jour 5/Nuit hotel jour 5 - 1.webp",
    photos: [
      "/images/Jour 5/Nuit hotel jour 5 - 1.webp",
      "/images/Jour 5/Nuit hotel jour 5 - 2.webp",
    ],
    ville: "Cappadoce",
    gps: "37.8746,32.4932",
    history: "Konya est l'une des plus anciennes villes d'Anatolie et une étape majeure de la Route de la Soie. Fief des Seldjoukides puis centre spirituel des derviches tourneurs, elle fut un carrefour commercial et culturel où les caravanes venaient échanger soie, épices et marchandises précieuses entre l'Orient et l'Occident.",
    anecdotes: [
      "Konya abrite le mausolée de Rûmi, fondateur de l'ordre des derviches tourneurs.",
      "La ville fut appelée 'Iconium' à l'époque romaine.",
      "Le haut plateau anatolien offre des paysages de steppe à perte de vue."
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://burcukayahotel.com/",
      },
    ],
  },
  {
    id: "trajet-cappadoce-konya",
    jour: [7],
    name: "De la Cappadoce à Konya",
    shortDesc: "Des paysages de Cappadoce aux terres spirituelles de Konya",
    tag: "Trajet",
    ville: "Cappadoce",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 7/Cappadoce - Konya 1.webp",
      "/images/Jour 7/Cappadoce - Konya 2.webp",
      "/images/Jour 7/Cappadoce - Konya 3.webp",
      "/images/Jour 7/Cappadoce - Konya 4.webp",
      "/images/Jour 7/Cappadoce - Konya 5.webp",
      "/images/Jour 7/Cappadoce - Konya 6.webp",
      "/images/Jour 7/Cappadoce - Konya 7.webp"
    ],
    audioTitle: "Sur la route de Konya",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Sur_la_route_de_Konya.mp3",
    gps: "37.8715,32.4846",
    historyLabel: "Le trajet",
    history:
      "Nous quittons maintenant les paysages extraordinaires de la Cappadoce pour prendre la direction de Konya, au cœur de l'Anatolie. Pendant le trajet, les cheminées de fées et les vallées sculptées dans la roche vont progressivement laisser place aux vastes plaines de l'Anatolie centrale, aux grandes étendues agricoles et aux collines arides. Cette région est profondément marquée par l'histoire : depuis l'Antiquité, ces terres constituent un important passage entre l'est et l'ouest de l'Anatolie. Puis apparaît Konya, ancienne capitale du sultanat seldjoukide de Roum et ville de Rûmî, plus connu sous le nom de Mevlana. C'est ici que s'est développée la tradition des derviches tourneurs et leur célèbre cérémonie du Sema. Après les paysages spectaculaires de la Cappadoce, nous découvrons ainsi une autre facette de la Turquie, davantage tournée vers la spiritualité, la poésie et l'histoire.",

    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet relie Göreme et Konya sur environ 240 kilomètres.",
      "Les paysages de Cappadoce laissent progressivement place aux grandes plaines de l'Anatolie centrale.",
      "La région de Konya est l'une des grandes zones agricoles de Turquie.",
      "Konya fut la capitale du sultanat seldjoukide de Roum au Moyen Âge.",
      "La ville est intimement liée à Rûmî, dit Mevlana, poète et mystique du XIIIe siècle.",
      "Les derviches tourneurs et la cérémonie du Sema sont devenus des symboles de la culture spirituelle de Konya.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/G%C3%B6reme/Konya",
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/cappadocia_konya_route.html",
      },
    ],
  },
  {
    id: "caravanserail",
    jour: [7],
    name: "Caravansérail Seldjoukide",
    shortDesc: "Ancien relais de caravanes sur la Route de la Soie",
    tag: "Visite",
    ville: "Konya",
    image: "/images/Jour 7/Caravanserai_1.webp",
    photos: [
      "/images/Jour 7/Caravanserai_1.webp",
      "/images/Jour 7/Caravansérail.webp",
      "/images/Jour 7/Caravanserai_2.webp",
      "/images/Jour 7/Caravanserai_4.webp",
      "/images/Jour 7/Caravanserai_5.webp",
      "/images/Jour 7/Caravanserai_6.webp"
    ],
    audioTitle: "Les caravansérails, auberges du désert",
    audioDuration: "2 min 45 sec",
    audioSrc: "/audio/places/Caravanserail.mp3",
    gps: "38.2353,33.5493",
    history: "Les caravansérails seldjoukides étaient des relais fortifiés construits le long de la Route de la Soie pour abriter les caravanes, leurs chameaux et leurs marchandises. Ces impressionnantes structures en pierre offraient refuge, nourriture et sécurité aux voyageurs. Le Sultanhan près de Konya est l'un des plus beaux exemples conservés en Turquie.",
    anecdotes: [
      "Le Sultanhan pouvait accueillir jusqu'à 400 chameaux dans ses écuries.",
      "Les portes monumentales étaient richement sculptées de motifs géométriques et floraux.",
      "Les caravansérails étaient espacés d'une journée de marche, soit environ 30 km."
    ]
  },
  {
    id: "trajet-konya-pamukkale",
    jour: [7],
    name: "De Konya à Pamukkale",
    shortDesc: "Des grandes plaines d'Anatolie aux terrasses blanches de Pamukkale",
    tag: "Trajet",
    ville: "Konya",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 7/Konya Pamukkale 1.webp",
      "/images/Jour 7/Konya Pamukkale 2.webp",
      "/images/Jour 7/Konya Pamukkale 3.webp",
      "/images/Jour 7/Konya Pamukkale 4.webp",
      "/images/Jour 7/Konya Pamukkale 5.webp",
      "/images/Jour 7/Konya Pamukkale 6.webp"
    ],
    audioTitle: "Sur la route de Pamukkale",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Sur_la_route_de_Pamukkale.mp3",
    gps: "37.9204,29.1206",
    historyLabel: "Le trajet",
    history:
      "Nous quittons Konya pour prendre la direction de l'ouest de la Turquie et de Pamukkale. La route traverse d'abord les vastes plaines agricoles de l'Anatolie centrale avant de rejoindre progressivement des paysages plus vallonnés et montagneux. Ce trajet permet de découvrir une Turquie rurale, entre champs, villages, troupeaux et grandes étendues sauvages. À l'approche de Pamukkale, le paysage change une nouvelle fois et annonce l'arrivée dans une région célèbre pour ses sources thermales. Depuis des milliers d'années, leurs eaux riches en minéraux ont façonné les célèbres terrasses blanches qui ont donné à Pamukkale son nom de « château de coton ». Juste au-dessus se trouvent les vestiges de Hiérapolis, une ancienne cité antique construite autour de ces sources.",
    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet entre Konya et Pamukkale représente environ 390 kilomètres.",
      "La route traverse une grande partie de l'Anatolie centrale avant de rejoindre les paysages plus montagneux de l'ouest.",
      "Les plaines agricoles laissent progressivement place à des vallées et des reliefs plus marqués.",
      "Pamukkale signifie littéralement « château de coton » en turc.",
      "Les terrasses blanches ont été formées par des dépôts de carbonate de calcium laissés par les sources thermales.",
      "Le site de Pamukkale est associé aux ruines de l'ancienne cité de Hiérapolis.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/Konya/Pamukkale"
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/konya_pamukkale_route",
      }
    ],
  },
  {
    id: "pamukkale",
    jour: [7],
    name: "Pamukkale",
    shortDesc: "Les Châteaux de Coton, merveille naturelle — UNESCO",
    tag: "Découvrir",
    ville: "Pamukkale",
    image: "/images/Jour 7/Pamukkale_1.webp",
    photos: [
      "/images/Jour 7/Pamukkale_1.webp",
      "/images/Jour 7/Pamukkale_2.webp",
      "/images/Jour 7/Pamukkale_3.webp",
      "/images/Jour 7/Pamukkale_4.webp"
    ],
    audioTitle: "Pamukkale, la forteresse de coton",
    audioDuration: "3 min 20 sec",
    audioSrc: "/audio/places/Pamukkale.mp3",
    gps: "37.9137,29.1187",
    history: "Pamukkale, 'Château de Coton' en turc, est un site naturel unique formé par le dépôt de carbonate de calcium provenant de sources thermales sur une falaise de 200 mètres. Inscrit au patrimoine mondial de l'UNESCO avec les ruines d'Hierapolis, ce paysage blanc éblouissant attire des visiteurs depuis l'Antiquité, y compris Cléopâtre qui y aurait pris ses bains.",
    anecdotes: [
      "L'eau des sources thermales se maintient à environ 36 degrés Celsius toute l'année.",
      "Les terrasses naturelles ressemblent à des piscines enneigées en plein été.",
      "La ville antique d'Hierapolis fut construite au sommet de Pamukkale par les Romains."
    ]
  },
  {
    id: "hotel-pam-thermal",
    reservationDocumentIds: ["hotel-pamukkale-pam-thermal"],
    jour: [7],
    name: "PAM Thermal Hotel Pamukkale",
    shortDesc: "Une parenthèse thermale au cœur de Pamukkale",
    tag: "Hôtel",
    ville: "Pamukkale",
    image: "/images/Jour 7/Hotel jour 7 - 1.webp",
    photos: [
      "/images/Jour 7/Hotel jour 7 - 1.webp",
    ],
    gps: "37.9588,29.1244",
    historyLabel: "Présentation de l'hôtel",
    history:
      "Situé à proximité de Pamukkale, le PAM Thermal Hotel est un établissement 5 étoiles spécialisé dans l'expérience thermale. Installé dans un environnement verdoyant, l'hôtel profite des eaux thermales naturelles caractéristiques de la région de Denizli. Après la découverte des célèbres terrasses blanches et de l'ancienne cité de Hiérapolis, c'est une étape idéale pour profiter d'un moment de détente et découvrir l'une des traditions les plus anciennes de cette région : les bains thermaux.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Hôtel 5 étoiles situé dans la région de Pamukkale.",
      "Établissement réputé pour ses installations thermales et ses piscines d'eau chaude.",
      "Les eaux thermales constituent l'une des grandes particularités naturelles de la région.",
      "Une étape idéale pour se détendre après la découverte de Pamukkale et de Hiérapolis.",
      "L'hôtel permet de profiter de l'ambiance thermale caractéristique de cette partie de la Turquie.",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.pamthermal.com/",
      },
    ],
  },
  {
    id: "trajet-pamukkale-ephese",
    jour: [8],
    name: "De Pamukkale à Éphèse",
    shortDesc: "Des sources thermales de Pamukkale aux vestiges de la cité d'Éphèse",
    tag: "Trajet",
    ville: "Pamukkale",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 8/Pamukkale Ephese 1.webp",
      "/images/Jour 8/Pamukkale Ephese 2.webp",
      "/images/Jour 8/Pamukkale Ephese 3.webp",
      "/images/Jour 8/Pamukkale Ephese 4.webp",
      "/images/Jour 8/Pamukkale Ephese 5.webp",
      "/images/Jour 8/Pamukkale Ephese 6.webp",
    ],
    audioTitle: "Sur la route d'Éphèse",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Sur_la_route_d_Ephese.mp3",
    gps: "37.9391,27.3410",
    historyLabel: "Le trajet",
    history:
      "Nous quittons Pamukkale pour prendre la direction de l'ouest de la Turquie et de la cité antique d'Éphèse. Après les paysages minéraux et les terrasses blanches de Pamukkale, la route traverse les terres agricoles de l'intérieur de l'Anatolie avant de rejoindre progressivement les paysages plus verdoyants de la région égéenne. Les montagnes, les vallées, les oliviers et les cultures annoncent l'arrivée dans une région au climat méditerranéen. Notre destination est Éphèse, l'une des plus grandes cités de l'Antiquité, qui fut pendant des siècles un important centre commercial, culturel et religieux. Après avoir découvert les merveilles naturelles de Pamukkale, ce trajet nous conduit ainsi vers une nouvelle étape de notre voyage : un véritable retour dans l'Histoire.",
    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet entre Pamukkale et Éphèse représente environ 190 à 200 kilomètres selon l'itinéraire.",
      "Les paysages évoluent progressivement des plaines intérieures vers les reliefs et vallées de la région égéenne.",
      "La végétation devient plus méditerranéenne à mesure que l'on se rapproche d'Éphèse.",
      "La région est connue pour ses oliviers, ses vignes et ses terres agricoles fertiles.",
      "Éphèse fut l'une des grandes cités du monde antique et un important centre commercial.",
      "La cité antique abrite notamment la célèbre bibliothèque de Celsus et l'un des plus grands théâtres antiques de Turquie.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/Pamukkale/%C3%89ph%C3%A8se",
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/pamukkale_ephesus_route.html",
      },
    ],
  },
  {
    id: "ephese",
    jour: [8],
    name: "Ephèse",
    shortDesc: "La cité d'Artémis, joyau antique de Turquie",
    tag: "Visite",
    ville: "Éphèse",
    image: "/images/Jour 8/Ephese_1.webp",
    photos: [
      "/images/Jour 8/Ephese_1.webp",
      "/images/Jour 8/ephese_photo_1.webp",
      "/images/Jour 8/ephese_photo_2.webp",
      "/images/Jour 8/Ephese_2.webp",
      "/images/Jour 8/Ephese_3.webp",
      "/images/Jour 8/Ephese_4.webp"
    ],
    audioTitle: "Ephèse, cité de la déesse Artémis",
    audioDuration: "4 min 15 sec",
    audioSrc: "/audio/places/Ephese.mp3",
    gps: "37.9390,7.3410",
    history: "Ephèse est le site archéologique le plus célèbre de Turquie. Fondée par les Grecs puis prospérant sous l'Empire romain, elle abritait le temple d'Artémis, l'une des Sept Merveilles du monde antique. La bibliothèque de Celsius, le grand théâtre et la rue des Courètes témoignent encore aujourd'hui de la splendeur de cette cité qui comptait jusqu'à 250 000 habitants.",
    anecdotes: [
      "La bibliothèque de Celsius abritait jusqu'à 12 000 rouleaux de parchemin.",
      "Le théâtre d'Ephèse pouvait accueillir 24 000 spectateurs, plus que beaucoup d'arènes modernes.",
      "La rue des Courètes était pavée de marbre et éclairée la nuit par des lampes à huile.",
      "Selon la croyance la Vierge Marie a été amenée à Éphèse par Saint Jean l’évangéliste, après la crucifixion du Christ. Ils se sont échappés des persécutions à Jérusalem. Elle y sera cachée et protégée des romains. Elle demeurera à la Maison De La Vierge à Éphèse jusqu’à son assomption (le 15 août)."
    ]
  },
  {
    id: "trajet-ephese-izmir",
    jour: [8],
    name: "D'Éphèse à Izmir",
    shortDesc: "Des vestiges antiques d'Éphèse aux rives de la mer Égée",
    tag: "Trajet",
    ville: "Éphèse",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 8/Ephese Izmir 1.webp",
      "/images/Jour 8/Ephese Izmir 2.webp",
      "/images/Jour 8/Ephese Izmir 3.webp",
      "/images/Jour 8/Ephese Izmir 4.webp",
      "/images/Jour 8/Ephese Izmir 5.webp",
      "/images/Jour 8/Ephese Izmir 6.webp",
      "/images/Jour 8/Ephese Izmir - 7.webp",
      "/images/Jour 8/Ephese Izmir - 8.webp",
      "/images/Jour 8/Ephese Izmir - 9.webp",
      "/images/Jour 8/Ephese Izmir - 10.webp",
      "/images/Jour 8/Ephese Izmir - 11.webp",
    ],
    audioTitle: "Sur la route d'Izmir",
    audioDuration: "1 min 45 sec",
    audioSrc: "/audio/places/Sur_la_route_d_Izmir.mp3",
    gps: "38.4237,27.1428",
    historyLabel: "Le trajet",
    history:
      "Nous quittons Éphèse pour rejoindre Izmir, l'une des grandes villes de la côte égéenne. Après les vestiges antiques, la route traverse les paysages verdoyants de la région, entre collines, oliviers, vignobles et terres agricoles. Peu à peu, l'environnement devient plus urbain et annonce l'arrivée dans la grande baie d'Izmir. Fondée dans l'Antiquité sous le nom de Smyrne, la ville a connu les influences grecques, romaines, byzantines et ottomanes. Aujourd'hui, Izmir est une métropole moderne et dynamique, tournée vers la mer Égée et réputée pour son atmosphère méditerranéenne.",
    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet entre Éphèse et Izmir représente environ 80 kilomètres.",
      "La route traverse les paysages verdoyants de la région égéenne.",
      "Les oliviers et les vignobles sont très présents dans cette partie de la Turquie.",
      "Izmir est la troisième plus grande ville de Turquie.",
      "La ville était connue dans l'Antiquité sous le nom de Smyrne.",
      "Le front de mer, appelé Kordon, est l'un des lieux emblématiques d'Izmir.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/%C3%89ph%C3%A8se/Izmir",
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/ephesus_izmir_route.html",
      },
    ],
  },
  {
    id: "izmir-kusadasi",
    jour: [8],
    name: "Izmir",
    shortDesc: "La perle de la côte égéenne",
    tag: "Ville",
    ville: "Izmir",
    image: "/images/Jour 7/Izmir_1.webp",
    photos: [
      "/images/Jour 7/Izmir_1.webp",
      "/images/Jour 7/Izmir_2.webp",
      "/images/Jour 7/Izmir_3.webp",
      "/images/Jour 7/Izmir_4.webp"
    ],
    audioTitle: "Izmir, trésors de la côte égéenne",
    audioDuration: "4 min 15 sec",
    audioSrc: "/audio/places/Izmir_ou_Kusadasi.mp3",
    history: "Izmir est la troisième plus grande ville de Turquie et l'un des ports les plus anciens de la Méditerranée. Située sur la côte égéenne, elle mêle héritage gréco-romain, architecture ottomane et modernité. Kusadasi, à quelques kilomètres, est une station balnéaire réputée pour son port de croisières et sa proximité avec les ruines d'Éphèse. La route entre ces deux villes offre des panoramas spectaculaires sur la mer Égée.",
    anecdotes: [
      "Izmir fut connue sous le nom de Smyrne dans l'Antiquité, l'une des plus grandes cités de l'Empire romain.",
      "Kusadasi signifie 'l'île aux oiseaux' en turc, en référence à l'îlot qui domine son port.",
      "La promenade du Kordon à Izmir est l'un des lieux de rendez-vous préférés des habitants pour admirer le coucher de soleil."
    ]
  },
  {
    id: "hotel-park-inn-radisson-izmir",
    reservationDocumentIds: ["hotel-izmir-park-inn"],
    jour: [8],
    name: "Park Inn by Radisson İzmir",
    shortDesc: "Un hôtel moderne face à la baie d'Izmir",
    tag: "Hôtel",
    ville: "Izmir",
    image: "/images/Jour 8/hotels_Izmir.webp",
    photos: [
      "/images/Jour 8/hotels_Izmir.webp",
      "/images/Jour 8/Hotel jour 8 - 2.webp",
    ],
    gps: "38.4303,27.1377",
    historyLabel: "Présentation de l'hôtel",
    history:
      "Situé au cœur d'Izmir, le Park Inn by Radisson İzmir bénéficie d'un emplacement privilégié à proximité du front de mer et de la célèbre promenade du Kordon. Cet hôtel 4 étoiles propose un cadre moderne et confortable, idéal pour découvrir la ville à pied. Sa situation permet notamment de rejoindre facilement les principaux quartiers animés du centre-ville, les restaurants et les lieux emblématiques de la baie d'Izmir.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "Hôtel 4 étoiles situé dans le centre d'Izmir.",
      "À proximité immédiate du front de mer et de la promenade du Kordon.",
      "Emplacement pratique pour découvrir le centre-ville à pied.",
      "L'hôtel dispose notamment d'un restaurant, d'un bar et d'une terrasse avec vue sur la ville.",
      "Une bonne étape pour profiter de l'ambiance animée du centre d'Izmir en soirée.",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.radissonhotels.com/tr-tr/oteller/park-inn-izmir",
      },
    ],
  },
  {
    id: "trajet-izmir-bursa",
    jour: [9],
    name: "D'Izmir à Bursa",
    shortDesc: "De la mer Égée aux premières capitales ottomanes",
    tag: "Trajet",
    ville: "Izmir",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 9/Izmir - Bursa 1.webp",
      "/images/Jour 9/Izmir - Bursa 2.webp",
      "/images/Jour 9/Izmir - Bursa 3.webp",
      "/images/Jour 9/Izmir - Bursa 4.webp",
      "/images/Jour 9/Izmir - Bursa 5.webp",
      "/images/Jour 9/Izmir - Bursa 6.webp",
      "/images/Jour 9/Izmir - Bursa 7.webp",
      "/images/Jour 9/Izmir - Bursa 8.webp",
      "/images/Jour 9/Izmir - Bursa 9.webp",
      "/images/Jour 9/Izmir - Bursa 10.webp",
      "/images/Jour 9/Izmir - Bursa 11.webp",
      "/images/Jour 9/Izmir - Bursa 12.webp",
      "/images/Jour 9/Izmir - Bursa 13.webp",
    ],
    audioTitle: "Sur la route de Bursa",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Sur_la_route_de_Bursa.mp3",
    gps: "40.1950,29.0600",
    historyLabel: "Le trajet",
    history:
      "Nous quittons Izmir pour prendre la direction de Bursa, dans le nord-ouest de la Turquie. En quittant la baie d'Izmir, la route traverse les plaines fertiles de l'ouest de l'Anatolie, entre oliviers, vergers, champs et villages. Peu à peu, nous nous rapprochons de la mer de Marmara et des reliefs du nord-ouest de la Turquie. Le mont Uludağ, qui domine Bursa, apparaît progressivement à l'horizon. Bursa occupe une place majeure dans l'histoire du pays : elle fut la première grande capitale de l'Empire ottoman au XIVe siècle, avant que le pouvoir ne soit transféré à Edirne puis à Constantinople. La ville conserve de nombreux témoignages de cette période et reste également réputée pour ses sources thermales et sa gastronomie.",
    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet entre Izmir et Bursa représente environ 330 kilomètres selon l'itinéraire.",
      "La route traverse les plaines agricoles fertiles de l'ouest de l'Anatolie.",
      "Les oliviers, les vergers et les champs sont très présents dans cette région.",
      "Le mont Uludağ domine Bursa et culmine à plus de 2 500 mètres d'altitude.",
      "Bursa fut la première grande capitale de l'Empire ottoman au XIVe siècle.",
      "La ville est réputée pour ses sources thermales et pour l'İskender kebap, l'une de ses spécialités emblématiques.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/Izmir/Bursa",
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/izmir_bursa_route.html",
      },
    ],   
  },
  {
    id: "bursa",
    jour: [9],
    name: "Bursa",
    shortDesc: "Première capitale de l'Empire ottoman",
    tag: "Ville",
    ville: "Bursa",
    image: "/images/Jour 9/Bursa.webp",
    photos: [
      "/images/Jour 9/Bursa.webp",
    ],
    audioTitle: "Bursa, berceau de l'Empire ottoman",
    audioDuration: "3 min 50 sec",
    audioSrc: "/audio/places/Bursa.mp3",
    gps: "40.1950,29.0600",
    history: "Bursa fut la première capitale de l'Empire ottoman, conquise par Orhan Gazi en 1326. Nichée au pied du Mont Uludağ (l'antique Olympe de Mysie), elle conserve un riche patrimoine ottoman avec ses mosquées, ses mausolées et ses bains traditionnels. La ville est également réputée pour ses soies, ses kebabs et ses fruits confits.",
    anecdotes: [
      "La Mosquée Verte (Yeşil Camii) doit son nom aux carreaux de faïence vert émeraude qui la décorent.",
      "Les tombeaux des premiers sultans ottomans se trouvent dans le Mausolée Vert.",
      "Le Mont Uludağ (Mont Olympe) est aujourd'hui une importante station de ski."
    ]
  },
  {
    id: "mosquee-mausolee-verts",
    jour: [9],
    name: "Mosquée et Mausolée verts de Bursa",
    shortDesc: "Le remarquable complexe de Mehmed Ier, joyau de l'architecture ottomane primitive",
    tag: "Visite",
    ville: "Bursa",
    image: "/images/Jour 9/Mosquee verte 1.webp",
    photos: [
      "/images/Jour 9/mosquee_verte_et_mausolee_de_bursa_photo_1.webp",
      "/images/Jour 9/mosquee_verte_et_mausolee_de_bursa_photo_2.webp",
      "/images/Jour 9/mosquee_verte_et_mausolee_de_bursa_photo_3.webp",
      "/images/Jour 9/Mosquee verte 1.webp",
      "/images/Jour 9/Mosquee verte 2.webp",
      "/images/Jour 9/Mosquee verte 3.webp",
      "/images/Jour 9/Mausolee vert 1.webp",
      "/images/Jour 9/Mausolee vert 2.webp",
      "/images/Jour 9/Mausolee vert 3.webp",
      "/images/Jour 9/Mausolee vert 4.webp",
      "/images/Jour 9/Mausolee vert 5.webp",
      ],
    audioTitle: "La Mosquée et le Mausolée verts, joyaux de Bursa",
    audioDuration: "6 min 30 sec",
    audioSrc: "/audio/places/Mosqee-mausolee-verts.mp3",
    gps: "40.1829,29.0776",
    history:
    "Au cœur de Bursa, ancienne capitale de l'Empire ottoman, se trouve l'un des ensembles monumentaux les plus remarquables de la première architecture ottomane : le complexe de la Mosquée verte et du Mausolée vert. Commandée par le sultan Mehmed Ier (Çelebi Mehmed) après avoir réunifié l'Empire ottoman, la Mosquée verte fut édifiée entre 1412 et 1420. Son architecte, Hacı İvaz Pasha, ancien commandant militaire, conçut un édifice au plan en T inversé, richement décoré de carreaux turquoise et verts réalisés notamment par des maîtres artisans venus de Tabriz. Face à la mosquée se dresse le Mausolée vert (Yeşil Türbe), construit en 1421 par le fils et successeur de Mehmed Ier, le sultan Murad II. Cet élégant édifice octogonal abrite la tombe de Mehmed Ier ainsi que celles de plusieurs membres de sa famille. Ses façades et son intérieur sont ornés de magnifiques céramiques turquoise, de stuc et de bois sculpté. L'ensemble symbolise la renaissance de la puissance ottomane après une période de crise et compte parmi les plus beaux témoignages de l'architecture ottomane primitive.",
    anecdotes: [
    "La Mosquée verte doit son nom à ses célèbres décors de céramique aux nuances de vert et de turquoise, qui comptent parmi les plus raffinés de l'architecture ottomane primitive.",
    "Les décors en céramique de la mosquée ont été réalisés notamment par des artisans persans venus de Tabriz, témoignant des échanges artistiques entre le monde ottoman et la Perse.",
    "L'architecte Hacı İvaz Pasha était à l'origine un commandant militaire avant de devenir architecte au service du sultan Mehmed Ier.",
    "Mehmed Ier mourut en 1421, avant de voir achevée la décoration de la Mosquée verte. Son fils Murad II fit alors construire le Mausolée vert pour lui offrir une sépulture digne de son rang.",
    "Le Mausolée vert est reconnaissable à son plan octogonal et à son revêtement spectaculaire de céramiques turquoise.",
    "À l'intérieur du mausolée se trouve le sarcophage de Mehmed Ier, surmonté d'un turban de tissu brodé, ainsi que plusieurs autres sépultures de membres de la famille impériale.",
    "Le complexe de la Mosquée verte et du Mausolée vert constitue l'un des ensembles les plus emblématiques de Bursa, ancienne capitale ottomane."
    ],
  },

  {
    id: "trajet-bursa-istanbul",
    jour: [9],
    name: "De Bursa à Istanbul par le pont Osmangazi",
    shortDesc: "Dernière traversée avant le retour à Istanbul",
    tag: "Trajet",
    ville: "Bursa",
    image: "/images/Bus.webp",
    photos: [
      "/images/Jour 9/Bursa Istanbul 1.webp",
      "/images/Jour 9/Bursa Istanbul 2.webp",
      "/images/Jour 9/Bursa Istanbul 4.webp",
      "/images/Jour 9/Bursa Istanbul 5.webp",
      "/images/Jour 9/Bursa Istanbul 6.webp",
      "/images/Jour 9/Bursa Istanbul 7.webp",
      "/images/Jour 9/Bursa Istanbul 8.webp",
      "/images/Jour 9/Bursa Istanbul 9.webp",
      "/images/Jour 9/Bursa Istanbul 10.webp",
      "/images/Jour 9/Bursa Istanbul 11.webp",
      "/images/Jour 9/Bursa Istanbul 12.webp",
      "/images/Jour 9/Bursa Istanbul 13.webp",
      "/images/Jour 9/Bursa Istanbul 14.webp",
      "/images/Jour 9/Bursa Istanbul 15.webp",
      "/images/Jour 9/Bursa Istanbul 16.webp",
    ],
    audioTitle: "Sur la route du retour vers Istanbul",
    audioDuration: "2 min 00 sec",
    audioSrc: "/audio/places/Sur_la_chemin_de_reour_vers_Istanbul.mp3",
    gps: "40.7654,29.5170",
    historyLabel: "Le trajet",
    history:
      "Nous quittons Bursa pour rejoindre Istanbul en traversant la baie d'Izmit par le célèbre pont Osmangazi. Inauguré en 2016, cet impressionnant pont suspendu permet de franchir la baie de manière beaucoup plus rapide qu'auparavant. Long d'environ 2,7 kilomètres, il porte le nom d'Osman Gazi, fondateur de la dynastie ottomane. Après la traversée, la route poursuit son chemin à travers les paysages du nord-ouest de la Turquie avant de rejoindre progressivement l'immense agglomération d'Istanbul. Ce dernier trajet marque la fin de notre découverte de la Turquie, après avoir traversé l'Anatolie et découvert ses paysages, son histoire et ses grandes civilisations.",
    anecdotesLabel: "À observer pendant le trajet",
    anecdotes: [
      "Le trajet est d'environ 150 kilomètres entre Bursa et Istanbul",
      "Le pont Osmangazi franchit la baie d'Izmit, sur la mer de Marmara.",
      "Le pont mesure environ 2,7 kilomètres de long.",
      "Il a été inauguré en 2016 et porte le nom d'Osman Gazi, fondateur de la dynastie ottomane.",
      "La traversée permet d'éviter un long détour autour de la baie.",
      "Depuis le pont, on bénéficie d'un vaste panorama sur la mer de Marmara.",
      "En approchant d'Istanbul, le paysage devient progressivement beaucoup plus urbain.",
      "Ce trajet constitue la dernière étape de notre grand parcours à travers la Turquie.",
    ],
    links: [
      {
        label: "Ouvrir la carte interactive du trajet via google maps",
        url: "https://www.google.com/maps/dir/Bursa/Istanbul",
      },
      {
        label: "Ouvrir la carte interactive du trajet",
        url: "/visites-guidees/bursa_istanbul_osmangazi_route.html",
      },
    ],
  },
  {
    id: "osmangazi",
    jour: [9],
    name: "Pont d'Osmangazi",
    shortDesc: "Le géant des eaux turques",
    tag: "Découvrir",
    ville: "Bursa",
    image: "/images/Jour 9/Osmangazi_1.webp",
    photos: [
      "/images/Jour 9/Osmangazi_1.webp",
      "/images/Jour 9/Osmangazi_2.webp",
      "/images/Jour 9/Osmangazi_3.webp"
    ],
    audioTitle: "Osmangazi, un pont entre deux rives",
    audioDuration: "3 min 30 sec",
    audioSrc: "/audio/places/Le_pont_d_Osmangazi.mp3",
    gps: "40.4027,28.5353",
    history: "Le pont d'Osmangazi (Osman Gazi Köprüsü) est un pont suspendu spectaculaire qui enjambe le golfe d'Izmit, à environ 50 km au sud d'Istanbul. Inauguré le 1er juillet 2016, il porte le nom d'Osman Gazi, fondateur de l'Empire ottoman. Avec une travée centrale de 1 550 mètres et une longueur totale de 2 682 mètres, il était à son inauguration le quatrième plus long pont suspendu au monde. Les pylônes culminent à 252 mètres de hauteur et le tablier est suspendu à 64 mètres au-dessus de la mer. Il fait partie de l'autoroute Gebze-Orhangazi-Izmir (O-5) et a réduit le trajet Istanbul-Izmir de 10 heures à seulement 3h30, transformant radicalement les échanges entre la mer de Marmara et la côte égéenne.",
    anecdotes: [
      "Le temps de traversée du golfe d'Izmit est passé de 2 heures (en ferry) à seulement 6 minutes.",
      "34 000 tonnes d'acier, provenant de Roumanie, ont été utilisées pour sa construction.",
      "Le pont a été construit dans l'une des zones les plus sismiques du monde ; les pylônes reposent sur une base de gravier permettant un glissement en cas de séisme."
    ]
  },
 {
    id: "nuit-hotel-windsoer-2",
   reservationDocumentIds: ["hotel-istanbul-windsor"],
    jour: [9],
    name: "hôtel WINDSOR HOTEL & CONVENTION CENTER 5*",
    shortDesc: "Nuit à l'hôtel Windsor",
    tag: "Hôtel",
    ville: "Istanbul",
    image: "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
    photos: [
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 1.webp",
      "/images/Jour 2/Nuit hotel jour 1 et 2 - 2.webp",
    ],
    gps: "41.044255,28.9131665",
    historyLabel:"Présentation de l'hôtel",
    history:
      "Le Windsor Hotel & Convention Center est un établissement 5★ moderne situé dans le quartier de Bayrampaşa, à Istanbul. Il se distingue par son vaste centre de convention, ses chambres élégantes et ses installations haut de gamme : spa complet, piscines intérieure et extérieure, sauna, hammam, ainsi qu’un salon panoramique au 17ᵉ étage offrant une vue superbe sur la ville et la Corne d’Or.",
    anecdotesLabel: "Informations pratiques",
    anecdotes: [
      "1 chambre double et 1 chambre triple normalement réservées",
    ],
    links: [
      {
        label: "Site officiel de l'hôtel",
        url: "https://www.windsorhotelistanbul.com/",
      },
    ],
  },
  {
    id: "Istanbul-Nantes",
    reservationDocumentIds: ["vol-istanbul-nantes-to3421"],
    jour: [10],
    name: "Istanbul - Nantes",
    shortDesc: "Vol TO3421 - 14h00 -> 17h10",
    tag: "Vol",
    ville: "Istanbul",
    image: "/images/Vol/Istanbul Nantes.webp",
    photos: [
    ],
    historyLabel:"Détails du vol",
    gps: "41.2753,28.7519",
    history: "Vol Transavia **TO3421** de Istanbul (IST) à Nantes (NTE). Départ à **14h00** pour une arrivée à 17h10\n"+
    "**Sièges** : 15D, 15E, 15F, 16F, 16F\n"+
    "Priority boarding\n"+
    "**Réservation** : XBGN4C",
    anecdotesLabel:"Informations bagages",
    anecdotes: [
      "Petit sac à ranger devant soi : 40 x 30 x 20 cm",
      "Valise cabine à ranger dans le compartiment supérieur : 55 x 25 x 40 cm",
      "Le poids total des bagages à main ne doit pas dépasser 12 kg",
       "Bagages en soute de 30 kg maximum",
    ],
  },
];
